### ISSUE TITLE
unable to compile

### ISSUE THREAD

**Issue by tainnok** [HTMLCOIN/HTMLCOIN#1]
Hello,

i am not able to compile, i followed the Steps descriped in "Build on Ubuntu".

gcc --version:
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4

got the following error:

  CXX      cpp-ethereum/libevm/libbitcoin_common_a-VMFactory.o
In file included from /usr/include/boost/optional.hpp:15:0,
                 from /usr/include/boost/format/internals.hpp:20,
                 from /usr/include/boost/format.hpp:38,
                 from /usr/include/boost/math/policies/error_handling.hpp:31,
                 from /usr/include/boost/multiprecision/detail/default_ops.hpp:9,
                 from /usr/include/boost/multiprecision/detail/generic_interconvert.hpp:9,
                 from /usr/include/boost/multiprecision/number.hpp:22,
                 from /usr/include/boost/multiprecision/cpp_int.hpp:12,
                 from ./cpp-ethereum/libdevcore/Common.h:51,
                 from ./cpp-ethereum/libethcore/Common.h:28,
                 from ./cpp-ethereum/libethereum/ExtVM.h:26,
                 from cpp-ethereum/libevm/VMCalls.cpp:19:
/usr/include/boost/optional/optional.hpp: In instantiation of ‘void boost::optional_detail::optional_base<T>::construct(boost::optional_detail::optional_base<T>::argument_type) [with T = dev::eth::owning_bytes_ref; boost::optional_detail::optional_base<T>::argument_type = const dev::eth::owning_bytes_ref&]’:
/usr/include/boost/optional/optional.hpp:250:33:   required from ‘boost::optional_detail::optional_base<T>::optional_base(const boost::optional_detail::optional_base<T>&) [with T = dev::eth::owning_bytes_ref]’
/usr/include/boost/optional/optional.hpp:564:76:   required from ‘boost::optional<T>::optional(const boost::optional<T>&) [with T = dev::eth::owning_bytes_ref]’
cpp-ethereum/libevm/VMCalls.cpp:137:68:   required from here
/usr/include/boost/optional/optional.hpp:346:8: error: use of deleted function ‘dev::eth::owning_bytes_ref::owning_bytes_ref(const dev::eth::owning_bytes_ref&)’
        new (m_storage.address()) internal_type(val) ;
        ^
In file included from ./cpp-ethereum/libethereum/ExtVM.h:27:0,
                 from cpp-ethereum/libevm/VMCalls.cpp:19:
./cpp-ethereum/libevm/ExtVMFace.h:72:2: error: declared here
  owning_bytes_ref(owning_bytes_ref const&) = delete;
  ^
make[2]: *** [cpp-ethereum/libevm/libbitcoin_common_a-VMCalls.o] Error 1

**Comment by Bushstar** [comment]
Did you use the depends folder for dependencies as shown in the following?

I added a make clean to remove objects compiled so far.

**Linux 64bit**
git clone https://github.com/HTMLCOIN/HTMLCOIN.git
cd HTMLCOIN/
cd depends/
make HOST=x86_64-pc-linux-gnu
cd ..
rm -Rf src/cpp-ethereum/
git submodule update --init --recursive
./autogen.sh
./configure --prefix=`pwd`/depends/x86_64-pc-linux-gnu --without-gui --without-miniupnpc
make clean
make

**Linux 32bit**
git clone https://github.com/HTMLCOIN/HTMLCOIN.git
cd HTMLCOIN/
cd depends/
make HOST=i686-pc-linux-gnu
cd ..
rm -Rf src/cpp-ethereum/
git submodule update --init --recursive
./autogen.sh
./configure --prefix=`pwd`/depends/i686-pc-linux-gnu --without-gui --without-miniupnpc
make clean
make

**Comment by tainnok** [comment]
Hi,
thanks for the quick reply!

Yes, this workaround (regardless if i am already on the target platform or not) worked fine for me  :)
I got working (as it looks like to me) htmlcoind and also htmlcoin-cli following your instructions (without gui and miniupnpc).
Later i try also to compile with qt-gui and this also worked,
got a running gui and already started mining with a little script, i am super excited if/when i got my first result/block.
Thanks for your help  :)
