### ISSUE TITLE
Possible libssl-dev issue

### ISSUE THREAD

**Issue by calinv** [HTMLCOIN/HTMLCOIN#10]
This issue tracker is only for technical issues related to HTMLCOIN.

### Describe the issue
I think that is a potential problem with using my current libssl-dev because every time when I want to run "make" on the sources I receive an error like this:

_key.cpp: In function ‘bool EnsureLowS(std::vector<unsigned char>&)’:
key.cpp:149:19: error: invalid use of incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
     if (BN_cmp(sig->s, halforder) > 0) {
                   ^
In file included from /usr/include/openssl/ecdsa.h:10:0,
                 from key.cpp:17:
/usr/include/openssl/ec.h:1039:16: note: forward declaration of ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
 typedef struct ECDSA_SIG_st ECDSA_SIG;
                ^
key.cpp:151:19: error: invalid use of incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
         BN_sub(sig->s, order, sig->s);
                   ^
In file included from /usr/include/openssl/ecdsa.h:10:0,
                 from key.cpp:17:
/usr/include/openssl/ec.h:1039:16: note: forward declaration of ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
 typedef struct ECDSA_SIG_st ECDSA_SIG;
                ^
key.cpp:151:34: error: invalid use of incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
         BN_sub(sig->s, order, sig->s);
                                  ^
In file included from /usr/include/openssl/ecdsa.h:10:0,
                 from key.cpp:17:
/usr/include/openssl/ec.h:1039:16: note: forward declaration of ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
 typedef struct ECDSA_SIG_st ECDSA_SIG;_

I am using ubuntu 16.04 and I have libssl-dev version 1.1.0g-2.1
libssl-dev/xenial,now 1.1.0g-2.1+ubuntu16.04.1+deb.sury.org+1 amd64

#### If so, please list the steps to reproduce below:
1. Trying to build the wallet by running make
2.
3.

### Expected behaviour
I expect to build the wallet and the executable files to appear

### Actual behaviour
The build is crashing

### What version of HTMLCOIN are you using?
I have clone the repository from github so I suspect to be the last version

### Machine specs:
- OS: Ubuntu 16.04
- CPU: Intel 
- RAM: 16GB
- Disk size:

**Comment by Bushstar** [comment]
Please use the dependencies that come with HTMLCOIN and not use system libs.

**64bit Linux**
```
git clone https://github.com/HTMLCOIN/HTMLCOIN.git
cd HTMLCOIN/
cd depends/
make HOST=x86_64-pc-linux-gnu
cd ..
rm -Rf src/cpp-ethereum/
git submodule update --init --recursive
./autogen.sh
./configure --prefix=`pwd`/depends/x86_64-pc-linux-gnu --without-gui --without-miniupnpc
make
```
