### ISSUE TITLE
Only 8-9 connections possible

### ISSUE THREAD

**Issue by smogm** [HTMLCOIN/HTMLCOIN#11]
The wallet is only connecting to 8 - 9 peers while maxconnections is set to 125.

**Comment by sunk818** [comment]
I have 12 connections now. Earlier in the day, I had 82 connections. I can't replicate your issue. It might be specific to your particular setup. Not that I'd know how to address low peer counts, but knowing what version wallet you are using and OS (version, 32-bit vs 64-bit) might help troubleshoot. 

What have you tried already?

Have you tried adding nodes manually to see if  your peer count goes up?

**Comment by myfreelyft** [comment]
I have the same issue, only have 8 connections.  How to I set the max connections higher?  Isnt it set at 125 by default?  I also noticed all my connections are outbound.

**Comment by mbootsman** [comment]
Same issue here. Only 8 connections. Version:  v2.0.1.0-beta (64-bit) - Linux
