### ISSUE TITLE
htmlcoind - CreateNewBlock: TestBlockValidity Failed: bad-version (code 17)

### ISSUE THREAD

**Issue by kfeaginsiii** [HTMLCOIN/HTMLCOIN#12]
This issue tracker is only for technical issues related to HTMLCOIN.

### Describe the issue
htmlcoind - CreateNewBlock: TestBlockValidity Failed: bad-version (code 17) occurs after running for a few minutes. Also noticed about 250 MB/S consistent read on my NVMe drive from this process. Not sure if this is unexpected or not. I do not see this drive contention from the gui generate.

### Can you reliably reproduce the issue?
Yes
#### If so, please list the steps to reproduce below:
1. Run the GUI, debug console, addnodes (not automatically picking them up)
2. debug console, generate 100 999999999
3. run htmlcoind in cm
4. spawn 3 start mining
5. wait about 10 minutes

### Screenshots.
![image](https://user-images.githubusercontent.com/20633228/34813072-209e39b4-f66e-11e7-8649-24811df01ffe.png)

### What version of HTMLCOIN are you using?
2.0.0.4 release

### Machine specs:
- OS: win10
- CPU: i7-6820HQ
- RAM: 16
- Disk size: 500 GB nvme

**Comment by Bushstar** [comment]
I only see the errors shown while the blockchain is still syncing with the network. Make sure that your block height is the same as shown in the explorer.

https://html.mastercalls.io/
