### ISSUE TITLE
Does staking work?

### ISSUE THREAD

**Issue by sahara108** [HTMLCOIN/HTMLCOIN#13]
Hi, I am using the latest version 2.0.0.4. I have tried to stake for a week but there no income at all. Does it work?

**Comment by Bushstar** [comment]
It works, the more coins you have the higher the chance that you will stake, there are open wallets with billions in who are minting the majority of PoS blocks. Leave it running for long enough and you will get a block. In the early days it was quite easy to mint blocks but as people have got more savvy about PoS mining it is getting harder and harder for people with less coins in their wallets.
