### ISSUE TITLE
Instructions to compile in Windows? 

### ISSUE THREAD

**Issue by sunk818** [HTMLCOIN/HTMLCOIN#15]
Curious to try out this branch: https://github.com/HTMLCOIN/HTMLCOIN/tree/getwork

Are there instructions on how to compile for Windows?

**Comment by Bushstar** [comment]
Cross compile, do not try to compile using mingw in msys or anything like that unless you are looking for a hard time. Either use Ubuntu or Windows Subsystem for Linux as the top of the instructions here tell you to do.

https://github.com/HTMLCOIN/HTMLCOIN/blob/getwork/doc/build-windows.md

If you are using WSL or Ubuntu please do the following to install build tools.

`sudo apt install build-essential libtool autotools-dev automake pkg-config bsdmainutils curl git`

64bit compiler
`sudo apt install g++-mingw-w64-x86-64`

32bit compiler
`sudo apt install g++-mingw-w64-i686 mingw-w64-i686-dev`

If you are using WSL or Ubuntu 16.04 or higher you need to set your compiler to posix or you will hit a nasty bug.

64bit compiler - WSL or Ubuntu 16.04 
```
sudo apt install software-properties-common
sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu zesty universe"
sudo apt update
sudo apt upgrade
sudo update-alternatives --config x86_64-w64-mingw32-g++ # Set the default mingw32 g++ compiler option to posix.
```

64bit compiler - Ubuntu 17.04 
`sudo update-alternatives --config x86_64-w64-mingw32-g++ # Set the default mingw32 g++ compiler option to posix.`

32bit compiler - WSL or Ubuntu 16.04 or 17.04
`sudo update-alternatives --config i686-w64-mingw32-g++  # Set the default mingw32 g++ compiler option to posix.`

Now we are ready to compile, follow these steps.

64bit build
```
git clone https://github.com/HTMLCOIN/HTMLCOIN.git
cd HTMLCOIN/
cd depends/
make HOST=x86_64-w64-mingw32
cd ..
rm -Rf src/cpp-ethereum/
git submodule update --init --recursive
./autogen.sh
./configure --prefix=`pwd`/depends/x86_64-w64-mingw32 --enable-static --disable-shared
make
```

32bit build
```
git clone https://github.com/HTMLCOIN/HTMLCOIN.git
cd HTMLCOIN/
cd depends/
make HOST=i686-w64-mingw32
cd ..
rm -Rf src/cpp-ethereum/
git submodule update --init --recursive
./autogen.sh
./configure --prefix=`pwd`/depends/i686-w64-mingw32 --enable-static --disable-shared
make
```

Congratulations, you now have the HTMLCOIN daemon, tools and Qt client.

**Comment by sunk818** [comment]
Great instructions. Installed Ubuntu on Windows 10 and ran the 64-bit build instructions. I got all the d, tx, and cli, but not qt. I don't need the Qt client, but are the instructions complete to build Qt?

I saw this in the README which I will try tonight:

`# If you want to build the Qt GUI:
sudo apt-get install libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler`

**Comment by Bushstar** [comment]
The required Qt libs should be compiled in the depends folder and picked up by configure. Run configure and see what it  says about Qt, try specifying it with...

./configure --prefix=`pwd`/depends/x86_64-w64-mingw32 --enable-static --disable-shared --with-qt

**Comment by gittygoo** [comment]
@Bushstar Where are the exe files located after compilation?

**Comment by sunk818** [comment]
Look in bin.

**Comment by Bushstar** [comment]
My binaries end up in...

HTMLCOIN/src - htmlcoind, htmlcoin-cli and htmlcoin-tx
HTMLCOIN/src/qt - htmlcoin-qt

**Comment by gittygoo** [comment]
@Bushstar any idea what this problem can be when running "make" ? 
I have rechecked that all dependencies are installed and instructions followed (Ubuntu 16.04.1 LTS)

`  CXX      leveldb/util/leveldb_libleveldb_a-env_win.o
leveldb/util/env_win.cc:887:8: error: 'port' does not name a type
 static port::OnceType once = LEVELDB_ONCE_INIT;
        ^
leveldb/util/env_win.cc: In static member function 'static leveldb::Env* leveldb::Env::Default()':
leveldb/util/env_win.cc:892:3: error: 'port' has not been declared
   port::InitOnce(&once, InitDefaultEnv);
   ^
leveldb/util/env_win.cc:892:19: error: 'once' was not declared in this scope
   port::InitOnce(&once, InitDefaultEnv);
                   ^
Makefile:7457: recipe for target 'leveldb/util/leveldb_libleveldb_a-env_win.o' failed
make[2]: *** [leveldb/util/leveldb_libleveldb_a-env_win.o] Error 1`

**Comment by Bushstar** [comment]
Build as per my instructions above, so do not use system libs but use the deps provided in the depends folder. I'll post the instructions for 32-bit Windows here. Note that you change into the depends directory and build the dependencies there. When you run configure you then point it to the depends folder. Make sure that making the deps finishes successfully.

```
git clone https://github.com/HTMLCOIN/HTMLCOIN.git
cd HTMLCOIN/
cd depends/
make HOST=i686-w64-mingw32
cd ..
rm -Rf src/cpp-ethereum/
git submodule update --init --recursive
./autogen.sh
./configure --prefix=`pwd`/depends/i686-w64-mingw32 --enable-static --disable-shared
make
```

If you still have issues compiling on 16.04 try Ubuntu 14, there were less issues compiling with 14, no need to use POSIX alternative compiler. I've got Ubuntu 14 on a VM for such tasks.
