### ISSUE TITLE
Wallet not connecting + Mining not working

### ISSUE THREAD

**Issue by Henry0191** [HTMLCOIN/HTMLCOIN#16]
### Describe the issue
I can't mine coins locally with CCminer. I followed the tutorial for Htmlcoin, but I always get
`[2018-01-18 13:31:07] JSON-RPC call failed: Method not found
[2018-01-18 13:31:07] get_work failed, retry after 30 seconds`

within CCminer console window.
Plus the wallet doesn't connect to the network.

### What version of HTMLCOIN are you using?
v2.0.0.4-beta

### Machine specs:
- OS: Windows 10
- CPU: i7-4770k
- RAM: 8GB
- Disk size: 200GB

**Comment by sunk818** [comment]
If you go to Help > Debug > Console and type `getwork`, you will see that is not a supported method.

You can only mine HTMLCOIN 2.0 using the GUI wallet. More details about mining here:
https://github.com/richardjoo/HTMLCOIN/tree/master/FAQ#mining

**Comment by Henry0191** [comment]
Thanks!
