### ISSUE TITLE
error: incorrect rpcuser or rpcpassword (authorization failed)

### ISSUE THREAD

**Issue by mbootsman** [HTMLCOIN/HTMLCOIN#17]
Getting error when querying with htmlcoin-cli 
`error: incorrect rpcuser or rpcpassword (authorization failed)`

#### If so, please list the steps to reproduce below:
1. start ~/Apps/HTMLCOIN/src/htmlcoind --daemon in rc.local
2. run ~/Apps/HTMLCOIN/src/htmlcoin-cli getinfo

### Expected behaviour
Get overview of wallet

### Actual behaviour
I get the error `error: incorrect rpcuser or rpcpassword (authorization failed)`

### What version of HTMLCOIN are you using?
2.0.0.4 / 932910b0b8ee8c1d5f015d8bba4371f82b9a16ce

### Machine specs:
- OS: Ububntu 16.04.3
- CPU:  AMD E-450
- RAM: 2GB
- Disk size: 64GB

Content /etc/rc.local

```
#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.

# start wallet
/home/myusername/Apps/HTMLCOIN/src/htmlcoind --daemon &

#start mining
/home/myusername/Apps/HTMLCOIN/htmlcoin-cli-mining.sh &
exit 0
```

**Comment by sunk818** [comment]
Do you have a htmlcoin.conf in same directory as src or was it the same directory as your wallet.dat

You downloaded the master branch ?

**Comment by mbootsman** [comment]
Hi, I just compiled the newest version: https://github.com/HTMLCOIN/HTMLCOIN/releases/tag/v2.0.1.0
Restarted and I get the same issue.

I have not specified the rpcuser/rpcpassword anywhere and there is no `htmlcoin.conf` in `~/.htmlcoin/` (where my `wallet.dat` is)
Here's the htmlcoin-cli-mining-sh script:
[htmlcoin-cli-mining.sh.txt](https://github.com/HTMLCOIN/HTMLCOIN/files/1685480/htmlcoin-cli-mining.sh.txt)
