### ISSUE TITLE
Error when trying to run the command make

### ISSUE THREAD

**Issue by miwand** [HTMLCOIN/HTMLCOIN#21]
### Describe the issue
Running make in the HTMLCOIN directory gives the following error:
  CXXLD    libbitcoinconsensus.la
clang: warning: argument unused during compilation: '-pthread' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-pthread' [-Wunused-command-line-argument]
Undefined symbols for architecture x86_64:
  "_SHA512_Final", referenced from:
      HMAC_SHA512_Init(HMAC_SHA512_CTX*, void const*, unsigned long) in libbitcoinconsensus_la-hash.o
      HMAC_SHA512_Final(unsigned char*, HMAC_SHA512_CTX*) in libbitcoinconsensus_la-hash.o
     (maybe you meant: __Z17HMAC_SHA512_FinalPhP15HMAC_SHA512_CTX)
  "_SHA512_Init", referenced from:
      HMAC_SHA512_Init(HMAC_SHA512_CTX*, void const*, unsigned long) in libbitcoinconsensus_la-hash.o
     (maybe you meant: __Z16HMAC_SHA512_InitP15HMAC_SHA512_CTXPKvm)
  "_SHA512_Update", referenced from:
      HMAC_SHA512_Init(HMAC_SHA512_CTX*, void const*, unsigned long) in libbitcoinconsensus_la-hash.o
      HMAC_SHA512_Update(HMAC_SHA512_CTX*, void const*, unsigned long) in libbitcoinconsensus_la-hash.o
      HMAC_SHA512_Final(unsigned char*, HMAC_SHA512_CTX*) in libbitcoinconsensus_la-hash.o
     (maybe you meant: __Z18HMAC_SHA512_UpdateP15HMAC_SHA512_CTXPKvm)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libbitcoinconsensus.la] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1

### What version of HTMLCOIN are you using?
List the version number/commit ID

### Machine specs:
- OS: 10.13.2 - Mac OS Sierra
- CPU: 2.6 GHz Intel Core i5
- RAM: 16 GB 1600 MHz DDR3
- Disk size: 250GB

### Any extra information that might be useful in the debugging process.
[config.log](https://github.com/HTMLCOIN/HTMLCOIN/files/1670534/config.log)

**Comment by Bushstar** [comment]
Try the following to reset and build using deps that came with HTMLCOIN.

```
git clean -fdx
cd depends
make HOST=x86_64-pc-linux-gnu
cd ..
rm -Rf src/cpp-ethereum/
git submodule update --init --recursive
./autogen.sh
./configure --prefix=`pwd`/depends/x86_64-pc-linux-gnu --disable-tests --disable-bench --enable-static --disable-shared
make
```

**Comment by miwand** [comment]
Thanks a ton! That worked I was able to successfully make it.
