### ISSUE TITLE
macOS cli binary 2.0.1: dyld: Library not loaded: /opt/local/lib/libboost_system-mt.dylib

### ISSUE THREAD

**Issue by sunk818** [HTMLCOIN/HTMLCOIN#23]
### Describe the issue

Getting error when trying to launch daemon.

Does error have to do with [Boost change](https://github.com/HTMLCOIN/HTMLCOIN/commit/fc5c0cd399189d4cb594e8fd71f0c12d939575f7)?

`MyMac:htmlcoind-2.0.1-mac me$ ./htmlcoind
dyld: Library not loaded: /opt/local/lib/libboost_system-mt.dylib
  Referenced from: /Users/me/Downloads/htmlcoind-2.0.1-mac/./htmlcoind
  Reason: image not found
Abort trap: 6
MyMac:htmlcoind-2.0.1-mac me$ 
`
#### If so, please list the steps to reproduce below:
1. Download and extract https://github.com/HTMLCOIN/HTMLCOIN/releases/download/v2.0.1.0/htmlcoind-2.0.1-mac.tar.gz
2. Run `htmlcoind`
3. Get error on macOS 10.12.6

### Expected behaviour

daemon should say: `HTMLCOIN server starting` and start syncing with the blockchain

### What version of HTMLCOIN are you using?

2.0.1 macOS pre-compiled CLI binaries.

### Machine specs:
- OS: macOS 10.12.6
- CPU: 2.8 GHz Intel Core i7
- RAM: 16 GB 2133 MHz LPDDR3

**Comment by Bushstar** [comment]
Does the desktop Mac wallet work? Looks like htmlcoind is locally linked to shared libs.

**Comment by Bushstar** [comment]
For some reason it did not pick up the statically linked libs and used system installed libs, rebuilding now.

**Comment by sunk818** [comment]
Confirming desktop wallet (DMG) works fine for me on macOS 10.12.6

**Comment by Bushstar** [comment]
Wallets now updated. Please try again.

**Comment by sunk818** [comment]
Perfect, no error this time. `htmlcoind --daemon` started up without error. Thanks for the quick turnaround.
