### ISSUE TITLE
htmlcoincore-node RPC method not found

### ISSUE THREAD

**Issue by docloulou** [HTMLCOIN/HTMLCOIN#24]
### Describe the issue
Hi i currently working on a Metamask-like app for browser, so i need to setup an API server for the HTML blockchain.
i currently succesfully install the htmlcoincore-node from your qtum fork but i got several Method not found from the API and the htmlcoincore-node + Insight API log

For example
`[AddressBalanceService] Update Error { RPCError: Method not found`
[image link](https://imgur.com/a/aF1bL)

/htmlcoin-api/blocks?
/htmlcoin-api/addr/[:addr]/utxo (and related address api (very important for my app))
`Method not found. Code:-32601`

I found other user with the same error on the qtum fork:
[https://github.com/qtumproject/qtum/issues/466](https://github.com/qtumproject/qtum/issues/466)

solution ?:
[https://github.com/qtumproject/qtumcore-node/pull/4](https://github.com/qtumproject/qtumcore-node/pull/4)

BTW the qtum team build a qtumD-bitcore version with extra RPC call i tried to edit the version.h and chainparam.ccp to get is work with the HTML network without any success.
[https://github.com/qtumproject/qtum-bitcore](https://github.com/qtumproject/qtum-bitcore)

So do you plan to do the same or can you provide a hotfix for theses error ?

Thanks

**Comment by Bushstar** [comment]
Did you download the Bitcore HTMLCOIN binary using the download script in the htmlcoincore-node/script folder?

Or compile your own from the Bitcore branch of HTMLCOIN.

https://github.com/HTMLCOIN/HTMLCOIN/tree/master-bitcore

**Comment by docloulou** [comment]
Oh my bad, i will give a try with the download script...

**Comment by docloulou** [comment]
BTW, your binaries are ready for the hard fork ?

**Comment by Bushstar** [comment]
Yes. If you run it you will see that it is the new version.
