### ISSUE TITLE
Wallet found empty - believe I deleted a folder by mistake, how do I restore my funds?

### ISSUE THREAD

**Issue by noobtrader1** [HTMLCOIN/HTMLCOIN#25]
Hi!

I opended my wallet and found it empty. I am suspecting I deleted a folder by mistake that belonged to the HTML WALLET setup. Is there a way of restoring my funds?
 Here is a copy of my transaction when I started my wallet.
Here is the transaction below from Bleutrade. Please help me! -87000.00000000 Withdraw: 86999.00000000 to address HczRGZyrwbfZDVpjuXkHENoHm43ts6cvKW; fee 1.00000000 (TXID 27b46376c0c841ac61e1067d38226b4ef78190b7780d2575b502c2d682534f81)

Kind regards,

This issue tracker is only for technical issues related to HTMLCOIN.

#### If so, please list the steps to reproduce below:
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of HTMLCOIN are you using?
List the version number/commit ID

### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by sunk818** [comment]
Download recuva on another computer and run on flash drive. Try to recover your old wallet dat

**Comment by noobtrader1** [comment]
Hi,

Recuva could not locate the wallet.dat file. Is there any other way of solving it?


Kind Regards,

Daniel
________________________________
Från: sunk818 <notifications@github.com>
Skickat: den 2 februari 2018 22:39:28
Till: HTMLCOIN/HTMLCOIN
Kopia: noobtrader1; Author
Ämne: Re: [HTMLCOIN/HTMLCOIN] Wallet found empty - believe I deleted a folder by mistake, how do I restore my funds? (#25)


Download recuva on another computer and run on flash drive. Try to recover your old wallet dat

**Comment by nayef22** [comment]
search in File Explorer type wallet.dat < its worked for me I found a copy in AppDate/Roaming/HTMLCOIN.

**Comment by HTMLCOIN** [comment]
Email help@htmlcoin.team
