### ISSUE TITLE
Not Updating Blockchain on Windows 10 After Update

### ISSUE THREAD

**Issue by dxhtml** [HTMLCOIN/HTMLCOIN#27]
**Not Updating Blockchain on Windows 10 After Update**

I Downloaded the update and ran the install into a subfolder
of C:\Program Files (x86)\HTMLCOIN
called it C:\Program Files (x86)\HTMLCOIN2\NEW VERSION

Because I was not sure how to backup old wallet and did not want to override it.

When I launch wallet coins are there but block is 
stuck at 106004 blocks.

Stuck at syncing headers 99.3%

Shows 14 connections
But, No green in progress bar.

Can someone help me to update correctly?

### Machine specs:
- OS: Windows 10 Home 64-bit
- CPU: Intel Core i5 4440
	    Cores	4

**Comment by MrJoeG** [comment]
Seems like I am having a similar issue. I checked my Windows Updates logs and don't show any recent updates other than Jan 9th. I was running fine just up until a couple of days ago when I had to reboot my cable modem while my mining cli was running.

**Comment by Lutz420** [comment]
I have the same issue after installing HTMLCOIN CORE Version v2.0.1.0-beta (32-Bit).

**Comment by Bushstar** [comment]
The clients should switch to the longer chain, I'm wondering if blocks adhering to an incorrect difficulty adjust is upsetting things somehow, I've overseen hard forks before and this usually is not an issue but then HTML is a hybrid coin.

Either, run the client again with -reindex in the shortcut as shown in the image below, or go to your data directory, %appdata%/HTMLCOIN and delete everything except your wallet.dat then start the client again.

https://i.imgur.com/RN7GblY.png

**Comment by HanMedSkon** [comment]
Nice the -reindex thing worked for me. thank you!
