### ISSUE TITLE
CreateNewBlock: TestBlockValidity failed: bad-version (code 17) (code -1)

### ISSUE THREAD

**Issue by supercel80** [HTMLCOIN/HTMLCOIN#28]
I got an error while mining:

CreateNewBlock: TestBlockValidity failed: bad-version (code 17) (code -1)

What does it mean and how to resolve?
Also the wallet isn't synchronize.

I have the HTMLCOIN CORE version v2.0.0.4-beta (32-bit)

Thanks!

![afbeelding](https://user-images.githubusercontent.com/36138609/35782172-adfda3fa-09f4-11e8-99e4-a9aba657cb27.png)

![afbeelding](https://user-images.githubusercontent.com/36138609/35782165-920f2484-09f4-11e8-87d0-d6a0554194b4.png)

**Comment by sunk818** [comment]
You need to upgrade to new wallet 2.0.1

If you still get error then try

`htmlcoin-qt -reindex` after you upgrade to latest version

**Comment by supercel80** [comment]
I updated the wallet. And run the command. But still the same errors.

![afbeelding](https://user-images.githubusercontent.com/36138609/35782300-33470320-09f6-11e8-9eb2-9a67d3f7438a.png)

![afbeelding](https://user-images.githubusercontent.com/36138609/35782315-512887e2-09f6-11e8-8725-d6afe955c81e.png)

Any suggestions please?

**Comment by sunk818** [comment]
Quit out your wallet
Go to command prompt
Go to c:\program files\Htmlcoin2
The type htmlcoin-qt -reindex 

Your program files will be program files (x86) if you are using windows 10 64-bit

**Comment by Buzz3210** [comment]
Sorry have not replied before but all sorted thanks for the advice.

**Comment by supercel80** [comment]
> Quit out your wallet
Go to command prompt
Go to c:\program files\Htmlcoin2
The type htmlcoin-qt -reindex
Your program files will be program files (x86) if you are using windows 10 64-bit

Thank you, this did the trick. My wallet is fully synchronised!
