### ISSUE TITLE
CheckProofOfWork amount too high / block header did not hash to a value lower than the specified target

### ISSUE THREAD

**Issue by hnstbndr** [HTMLCOIN/HTMLCOIN#29]
### Issue
I was wondering why I am not hitting any blocks. So I added some debug output to the code (results attached). Turns out my CheckProofOfWork amount is always too high (I ran generate a few million times), or, in other words:  the block header did not hash to a value lower than the specified target. How is that possible? Is my MacBook Pro early 2015 too powerful?
What I also did is check the blocks that have been generated before, and, worst part: their CheckProofOfWork amount is also too high to be accepted, but they were accepted... Any idea?
The CheckProofOfWork amount is not even fluctuating, and always stays way above the target.

### Steps to reproduce below:
1. Open wallet / start via console
2. generate 1 1000
3. check log

### Expected behaviour
The CheckProofOfWork amount should fluctuate more, or the target should be higher.

### Actual behaviour
CheckProofOfWork amount does not fluctuate.

### What version of HTMLCOIN are you using?
Latest version, 2.0.1

### Machine specs:
- OS: macOS 10.13.2
- CPU: 2.7 GHz Intel Core i5
- RAM: 16 GB
- Disk size: 250 GB

### Attachement
[debug.log](https://github.com/HTMLCOIN/HTMLCOIN/files/1698535/debug.log)

**Comment by sunk818** [comment]
You know I run generate a few Billion times and I don't get a block. It's not easy with high difficulty. The debug is correct. Your proof needs to be lower than the target to be accepted. The higher the difficulty, the harder it is to generate a lower number.

Concerning you are getting this message for every hash though. Debug will grow quickly.

**Comment by hnstbndr** [comment]
I put the debug output in the code, normally you would not see it. The difficulty does not seem to be too high, though. 43 atm of writing.
So the more hashes I can generate and check, the better my chances to get a block.

**Comment by sunk818** [comment]
The product is working as designed.

Are you complaining that you haven't gotten a block?

**Comment by hnstbndr** [comment]
yeah, happy to close!
