### ISSUE TITLE
Linux CLI, server not starting

### ISSUE THREAD

**Issue by fisken** [HTMLCOIN/HTMLCOIN#30]
This issue tracker is only for technical issues related to HTMLCOIN.

### Describe the issue
When I try to start the server with 
"htmlcoind -daemon" a message is displayed that the server is starting. But it never starts. 

This issue came up after the recent update before that everything was working. 

I tried removing the wallet with make uninstall, then deleting the folder and copy the new git hub after the update. 
Compiled with no error, but still not starting. 
### Can you reliably reproduce the issue?
Yes
#### If so, please list the steps to reproduce below:
1.htlmcoind -daemon
2.message displayed "HTMLCOIN server starting"
3. Looking in htop server not started

### Expected behaviour
Server should start

### Actual behaviour
Server doesn't start

### What version of HTMLCOIN are you using?
List the version number/commit ID
Newest

### Machine specs:
- OS: Linux vps
- CPU: 3 x 1,8 ghz
- RAM: 2 gb
- Disk size: 80 gb

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by Bushstar** [comment]
Please post the relevant contents of the debug.log.
