### ISSUE TITLE
PEERS banned

### ISSUE THREAD

**Issue by Abdelhaq75** [HTMLCOIN/HTMLCOIN#31]
This issue tracker is only for technical issues related to HTMLCOIN.

### Describe the issue
After upgrqding from v2.0.0.2 to 2.0.1.0 , all my peers seem to be banned and appear in the section "BANNED PEERS". I performed a "-reindex" in the hope that would solve the issue... I downgraded back to 2.0.0.4 and 2.0.0.2 but the issue persists. At the moment, I'm back on 2.0.1.0, but it is still the same

### Can you reliably reproduce the issue?
YES

#### If so, please list the steps to reproduce below:
1. Start the wallet
2. Unlock the Wallet
3. View PEERS tab

### Expected behaviour
Peers should be connectable

### Actual behaviour
All my peers are in the section "BANNED PEERS". When unbanning the peers, they immediately flip back to banned or disappear. I rebooted my router, but to no avail.

### Screenshots.
![2018-02-11_14-38-44](https://user-images.githubusercontent.com/22117678/36074004-ebe47410-0f39-11e8-81bc-67273e55ab0a.png)

### What version of HTMLCOIN are you using?
v2.0.1.0-beta

### Machine specs:
- OS: Win10 Pro x64
- CPU: i5-3570K
- RAM: 16GB
- Disk size: 80GB SSD

### Any extra information that might be useful in the debugging process.
[debug.log](https://github.com/HTMLCOIN/HTMLCOIN/files/1714401/debug.log)

Any help is appreciated...

### UPDATE:
After hours leaving my computer running and wallet unlocked, I have 3 connections and 66 banned peers. Also, I'm still unable to stake, it keeps returning the message "not staking because wallet is syncing".
![2018-02-11_21-13-44](https://user-images.githubusercontent.com/22117678/36077895-8a0c83e0-0f70-11e8-8307-0d7c6211e132.png)

**Comment by Bushstar** [comment]
It is banning all those pre-fork nodes as they are trying to serve your client blocks that are now invalid port-fork.
