### ISSUE TITLE
Android: No PIN is required when turning off the Touch ID

### ISSUE THREAD

**Issue by vsabolc** [HTMLCOIN/HTMLCOIN#33]
@senagbe 

Steps to reproduce:
- Open the app
- Tap on the Profile
- Tap on Touch ID
- The option will be turned off and there is no PIN request popup displayed at all
- PIN verification have to be done before turning off the Touch ID

**Comment by dohaivu** [comment]
@senagbe please review it

**Comment by sunk818** [comment]
Do Android issues go here? https://github.com/HTMLCOIN/htmlcoin-android/issues

**Comment by Bushstar** [comment]
Again please raise this in the appropriate repo, this is HTMLCOIN Core.
