### ISSUE TITLE
Android: Incorrect error message was displayed when started the app with no internet connection

### ISSUE THREAD

**Issue by vsabolc** [HTMLCOIN/HTMLCOIN#34]
@senagbe 

Steps to reproduce:
- Open the Android app
- Kill internet connection
- Login
- Check the displayed page
- There is an error message displayed at the bottom of the screen - check the screenshot
- The message is not correct
![nointernet-error](https://user-images.githubusercontent.com/4669689/36597539-bc257bba-18a9-11e8-8765-a89139aae9e7.png)

**Comment by dohaivu** [comment]
This error is because the server is offline. It will show another message.

**Comment by sunk818** [comment]
Do Android issues go here? https://github.com/HTMLCOIN/htmlcoin-android/issues

**Comment by Bushstar** [comment]
Please raise this on the correct HTMLCOIN repo as sunk818 has kindly linked in his above response.
