### ISSUE TITLE
The Manage Addresses does not have all used address displayed

### ISSUE THREAD

**Issue by vsabolc** [HTMLCOIN/HTMLCOIN#35]
@senagbe 

Steps to reproduce:
- Open device 1
- Send HTML coin to an address
- Check the Manage Addresses
- It does not have the used address
- Receive HTML coin from the same address
- Check the Manage Addresses
- It does not have the used address

![addresses1](https://user-images.githubusercontent.com/4669689/36598616-1448c510-18ad-11e8-8f7e-c029fd00ee50.PNG)
![missingaddress](https://user-images.githubusercontent.com/4669689/36598618-1468fe0c-18ad-11e8-9a85-48308da748b5.PNG)

**Comment by dohaivu** [comment]
Yes, it works that way.
`Manage Addresses` is a list of 10 addresses managed by private key that stored in device. 
Which means that you can use any of 10 address to receive the HTML coins.

**Comment by Bushstar** [comment]
This does not apply to the HTMLCOIN Core wallet on which you are raising the issue.
