### ISSUE TITLE
Suggestion: Make possible to IMPORT a QR code from a PDF or IMAGE and not just use the QR code scanner

### ISSUE THREAD

**Issue by vsabolc** [HTMLCOIN/HTMLCOIN#36]
@senagbe 

At this moment the users can only scan a QR code what is printed or on the monitor or any other device.

Suggestion:
- Make possible to import a PDF  or image and scan it inside the app and that way the users can easily scan an address what they received on their mobile phone
(possible solution can be to instruct the users to make a screenshot from the page where they have opened the email-in the email app- and after import that image and scan that image and read the qr code from that file)

**Comment by Bushstar** [comment]
HTMLCOIN Core wallet will not implement this feature but will remain somewhat vanilla to be as compatible as possible with upstream changes from Bitcoin and Qtum. Alternative wallet implementations would be best suited for bespoke and more advanced features, for example the Core wallet in Bitcoin is somewhat simple compared to some of the other wallets on offer by third parties. Coins that bolt on bells and whistles to their wallet software often have trouble then moving the codebase to newer releases.
