### ISSUE TITLE
2.0.1 htmlcoind Error: -daemon is not supported on this operating system

### ISSUE THREAD

**Issue by sunk818** [HTMLCOIN/HTMLCOIN#37]
whenever I try to run htmlcoind on Windows 10, I get this error. 

`C:\apps\htmlcoind-2.0.1-win32\htmlcoind-2.0.1-win32>htmlcoind
Error: -daemon is not supported on this operating system`

I don't have this issue on Windows 7. 

The command prompt usually is locked to this process and the window remains in task bar.

htmlcoind just gives this error and exits. Not sure if this is a new issue from Windows 10 update?
I tried running compatibility and changing it to Windows 8 and Windows 7. Neither did anything different.

**Comment by sunk818** [comment]
taking htmlcoin.conf out of %appdata%\HTMLCOIN seems to have removed the behavior

**Comment by Bushstar** [comment]
Was daemon=1 specified in the htmlcoin.conf file?
