### ISSUE TITLE
UTXOcache mandatory update

### ISSUE THREAD

**Issue by Bushstar** [HTMLCOIN/HTMLCOIN#39]
There seems to be an issue with the UTXO cache as discovered when working with the mobile wallets, this issue is assumed to also be in Qtum. A recent release from Qtum includes a mandatory update with a UTXO cache fix which could well be applicable.

https://github.com/qtumproject/qtum/commit/e12196092c4182d77947c001a1f50de6c12ec035

This upstream fix should also be applied to HTMLCOIN and as it is mandatory with a block height for switching over this change needs to be planned for with at least a couple of weeks notice before activating on the network.

**Comment by senagbe** [comment]
@Bushstar agreed, this should fix the issues we've been having with the mobile clients and allow us to open up the mobile testing https://github.com/HTMLCOIN/htmlcoin-android/issues/3

**Comment by Bushstar** [comment]
Mandatory update applied in 2.0.3.0.

https://github.com/HTMLCOIN/HTMLCOIN/releases/tag/v2.0.3.0

**Comment by HTMLBunker** [comment]
@senagbe i am having the same issue with Unspent Outputs blocking me to send coins to another wallet. 
![7a305d3d-4ce1-4169-aab9-5c896fe27e72](https://user-images.githubusercontent.com/38928791/39967781-4061dfdc-5698-11e8-9c55-c8c4e80db3b7.jpg)

**Comment by HTMLBunker** [comment]
Solved. We found a wallet (sender wallet) that has -100 in balance. We send 100 to balance. Now the wallet is able to send. But the message appears again when we try to send big ammounts of coins. Maybe related to this https://www.reddit.com/r/Qtum/comments/82lk7m/losing_qtums_while_staking/
