### ISSUE TITLE
Wallet not connecting to peers 

### ISSUE THREAD

**Issue by nmorenless** [HTMLCOIN/HTMLCOIN#4]
### Describe the issue
The HTMLCoin wallet 2.0.0.2 and 2.0.0.3 is not connecting to peers. There are 0 active connections to the HTMLCoin network. I have no firewall nor filter software. My internet works fine otherwise.

I've installed 2.0.0.2, rebooted, reinstalled, uninstalled, tried 2.0.0.3, rebooted, reinstalled. I've removed all related files after backing up wallet on desktop, same issue. See screenshot. It appears there are a lot of people on the reddit forum having the same issue. 

### Screenshots.
![screen shot 2018-01-06 at 1 08 57 pm](https://user-images.githubusercontent.com/35175197/34642595-8e53c502-f2e3-11e7-9b73-a3e732a56a3c.png)

### Machine specs:
- OS: MacOS Sierra 10.12.6
- CPU: 2.3 intel i7
- RAM: 8gb
- Disk size: 40gb free

**Comment by Bushstar** [comment]
There's a bug with new clients not being able to connect, try connecting manually with the following command in the debug console using IP addresses from the linked in text document. A new client will be coming out in the next couple of days with this connection issue fixed.

addnode 165.227.147.196 add

https://pastebin.com/VXj0MNqt

**Comment by nmorenless** [comment]
That got things moving, thank you very much!

**Comment by Kzdor** [comment]
we have question Bushstar it is very important 

Dear HTMLCoinFoundation Thank you very much for your hard work.

We have a few questions.

How many developers are on the htmlcoin team?

How many teams are working?..

Where POMA github project is?

We have infinite trust.

Please reply.

**Comment by Bushstar** [comment]
I work on the core coin and we pull from the upstream Qtum project.

As to POMA I am not involved with that project.

**Comment by boldekrol** [comment]
I send html5coin amount from yobit to my recently installed htmlcoinwallet on mac. Went thru the protocol on htmlcoin website to swap. Now i am unable to sync my wallet completely. It always stalls (see picture). According to yobit my withdrawal went thru, so not showing up anymore on my balance.

Please help
<img width="956" alt="schermafbeelding 2018-01-07 om 14 09 58" src="https://user-images.githubusercontent.com/28260892/34649718-c0e457a8-f3b4-11e7-927f-c09cca8fe5bc.png">

**Comment by Bushstar** [comment]
They should be in there by now, the swap server had run out of coins and has now been topped up.

**Comment by boldekrol** [comment]
Thank for reply, and yes i got them.

**Comment by MrSlagovich** [comment]
I can't get any peers to connect and when i add nodes the console prints out null

**Comment by Bushstar** [comment]
Newly set up clients seem to be okay, older nodes may be banned and ignored by the external clients they connected to. I've got some new 2.0.0.4 nodes from the seeder you could try with addnode, it does return null so that is correct.

https://pastebin.com/3S0DUDue

It may also be worth restarting your router to try and appear to be a different node.

**Comment by MrSlagovich** [comment]
Ok cheers for the info, after adding all the IP addresses I have 2 active connections so hopefully i can sync back up

**Comment by MrSlagovich** [comment]
I added all the peer IPs and left it running for 14 hours and the connections were at 2 for a little bit but the rest of the time it's been at 0 and not synced. I've mined 700,000 html while not being able to sync so i've got a feeling i've been mining offline. Either way my wallet sync is 17 hours behind

**Comment by kfeaginsiii** [comment]
Not sure if we should re-open this issue. I am on 2.0.0.4 and having issues connecting to nodes.

![image](https://user-images.githubusercontent.com/20633228/34812536-a4aeda40-f66b-11e7-9cfe-bb86f7f728ff.png)

I have to go through and manually add them. Getting the cli htmlcoind working has been tricky.

**Comment by Bushstar** [comment]
Restart your router and try again. Seems that nodes that previously seen are ignored by other network nodes, run a new client on a different port and it connects. Restarting the router may give you a new IP or map your client to a different port and appear as a different node to the network.

**Comment by Deki63** [comment]
Greetings, i have problems with conection, when i open the htmlcoin app, it just opens the overview window and it doesnt mine anything...at the bottom right it says : not staking because i dont have mature coins: what do i do? how do i continue minning? thanks

**Comment by supercel80** [comment]
I got an error:

  | CreateNewBlock: TestBlockValidity failed: bad-version (code 17) (code -1)

What does it mean and how to resolve?

**Comment by tiraxturumuz** [comment]
I have this problem
