### ISSUE TITLE
build error ubuntu

### ISSUE THREAD

**Issue by yatson1** [HTMLCOIN/HTMLCOIN#41]
Error with build in ubuntu
                 from rpc/mining.cpp:21:
rpc/mining.cpp: In function ‘UniValue getwork(const JSONRPCRequest&)’:
rpc/mining.cpp:590:16: error: ‘pwalletMain’ was not declared in this scope
         assert(pwalletMain != NULL);
                ^
rpc/mining.cpp:591:62: error: ‘pMiningKey’ was not declared in this scope
         return CheckWork(chainParams, pblock, *pwalletMain, *pMiningKey);
                                                              ^
rpc/mining.cpp:593:1: warning: control reaches end of non-void function [-Wreturn-type]

**Comment by Bushstar** [comment]
That's odd as I've compiled it on Ubuntu and looking at the code those variables are present, just ran a clean build again to double check without this issue.

Try to reset, make sure you are on the correct branch, full up-to-date and start over.

```
git reset --hard HEAD
git checkout master
git pull
git clean -fdx
./autogen.sh
./configure --enable-static --disable-shared
make
```

**Comment by syndrael** [comment]
If you could help me [Make issue on Debian Stretch](https://github.com/HTMLCOIN/HTMLCOIN/issues/48) .. 
I've tried ./configure --enable-static --disable-shared ..but unsuccessful
Regards.
