### ISSUE TITLE
Any info how to mine with GPU?

### ISSUE THREAD

**Issue by markoffk** [HTMLCOIN/HTMLCOIN#42]
Hello.
Would be nice to get info how to mine coins via GPU. I am using generatetoaddress command but it seems that it uses only CPU.

OS: Ubuntu 17.10
GPU: nvidia 960gtx, nvidia drivers installed

**Comment by sunk818** [comment]
https://t.me/HTMLmining

This group is strictly focused on the mining of HTMLCoin. It's an unofficial group and we are all here to help each other mining this coin.

Rules:
1. No spam
2. Don't promote other coins
3. No referral links "ban"

**Comment by fogoat** [comment]
Also look at wiki here . There are links there
