### ISSUE TITLE
Compile error on Ubuntu 16.4.0.4 LTS

### ISSUE THREAD

**Issue by Netzarim** [HTMLCOIN/HTMLCOIN#43]
CXX      libbitcoin_server_a-init.o
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
Makefile:9056: recipe for target 'libbitcoin_server_a-init.o' failed
make[2]: *** [libbitcoin_server_a-init.o] Error 4
make[2]: Leaving directory '/root/HTMLCOIN/src'
Makefile:13710: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/HTMLCOIN/src'
Makefile:693: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by Bushstar** [comment]
You are most likely out of RAM, either add swap or more RAM, 1.5GB per thread.
