### ISSUE TITLE
HTMLCOIN quit unexpectedly macOS 10.12.6

### ISSUE THREAD

**Issue by sunk818** [HTMLCOIN/HTMLCOIN#44]
This doesn't always happens, but it happens frequently when I use the `-server` parameter when I launch `HTMLCOIN-qt` from command line. I do want to quit, but I get this error message after I quit. 

Is there a similar `htmlcoin-cli stop` for `HTMLCOIN-qt`? 

Process:               HTMLCOIN-qt [81317]
Path:                  /Applications/HTMLCOIN-Qt.app/Contents/MacOS/./HTMLCOIN-qt
Identifier:            com.htmlcoin.HTMLCOIN-Qt
Version:               2.0.2 (2.0.2)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           HTMLCOIN-qt [81317]
User ID:               501

Date/Time:             2018-03-01 15:24:26.679 -0800
OS Version:            Mac OS X 10.12.6 (16G1212)
Report Version:        12
Anonymous UUID:        D92A76BF-2D14-3704-C85F-1B419627BC41

Sleep/Wake UUID:       4BA45FA3-820F-4E1C-87CC-94C2E9E11661

Time Awake Since Boot: 1900000 seconds
Time Since Wake:       1900000 seconds

System Integrity Protection: disabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
Assertion failed: (!pthread_mutex_lock(&m)), function lock, file /Users/user/Desktop/HTMLCOIN/depends/x86_64-apple-darwin14.0.0/share/../include/boost/thread/pthread/recursive_mutex.hpp, line 113.

**Comment by fogoat** [comment]
It had to do with laptop temp being too high.
