### ISSUE TITLE
Make issue on Debian Stretch

### ISSUE THREAD

**Issue by syndrael** [HTMLCOIN/HTMLCOIN#48]
Hello, 
I can't execute Make -j2 successfully.
I can reliably reproduce the issue?
What version of HTMLCOIN are you using?
List the version number --> HTMLCOIN 2.0 downloaded today
Thx for your help.

### Machine specs:
- OS: Debian Stretch
- CPU: Core i5
- RAM: 8Go
- Disk size: 240 Go SSD 
--------------------------------------------------------------------------
Making all in src
make[1]: Entering directory '/home/myhome/Documents/HTMLCOIN/src'
make[2]: Entering directory '/home/myhome/Documents/HTMLCOIN/src'
  CXX      libbitcoinconsensus_la-arith_uint256.lo
  CXX      libbitcoinconsensus_la-hash.lo
  CXX      libbitcoinconsensus_la-pubkey.lo
  CXX      libbitcoinconsensus_la-uint256.lo
  CXX      libbitcoinconsensus_la-utilstrencodings.lo
make[3]: Entering directory '/home/myhome/Documents/HTMLCOIN/src/secp256k1'
gcc -I. -g -O2 -Wall -Wextra -Wno-unused-function -c src/gen_context.c -o gen_context.o
gcc gen_context.o -o gen_context
  CC       src/java/libsecp256k1_jni_la-org_bitcoin_NativeSecp256k1.lo
  CC       src/java/libsecp256k1_jni_la-org_bitcoin_Secp256k1Context.lo
./gen_context
  CCLD     libsecp256k1_jni.la
/usr/bin/ar: `u' modifier ignored since `D' is the default (see `U')
  CC       src/libsecp256k1_la-secp256k1.lo
  CXX      htmlcoind-bitcoind.o
  CCLD     libsecp256k1.la
/usr/bin/ar: `u' modifier ignored since `D' is the default (see `U')
make[3]: Leaving directory '/home/myhome/Documents/HTMLCOIN/src/secp256k1'
  CXX      libbitcoin_server_a-addrman.o
  CXX      libbitcoin_server_a-addrdb.o
  CXX      libbitcoin_server_a-alert.o
  CXX      libbitcoin_server_a-bloom.o
  CXX      libbitcoin_server_a-blockencodings.o
  CXX      libbitcoin_server_a-chain.o
  CXX      libbitcoin_server_a-checkpoints.o
In file included from ./qtum/qtumstate.h:9:0,
                 from validation.h:37,
                 from blockencodings.cpp:13:
./qtum/qtumtransaction.h: In static member function ‘static VersionVM VersionVM::fromRaw(uint32_t)’:
./qtum/qtumtransaction.h:24:37: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
         VersionVM x = *(VersionVM*)&val;
                                     ^~~
./qtum/qtumtransaction.h:24:37: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
In file included from ./qtum/qtumstate.h:9:0,
                 from validation.h:37,
                 from checkpoints.cpp:9:
./qtum/qtumtransaction.h: In static member function ‘static VersionVM VersionVM::fromRaw(uint32_t)’:
./qtum/qtumtransaction.h:24:37: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
         VersionVM x = *(VersionVM*)&val;
                                     ^~~
./qtum/qtumtransaction.h:24:37: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  CXX      libbitcoin_server_a-checkpointsync.o
  CXX      libbitcoin_server_a-httprpc.o
In file included from ./qtum/qtumstate.h:9:0,
                 from ./validation.h:37,
                 from txdb.h:20,
                 from checkpointsync.cpp:60:
./qtum/qtumtransaction.h: In static member function ‘static VersionVM VersionVM::fromRaw(uint32_t)’:
./qtum/qtumtransaction.h:24:37: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
         VersionVM x = *(VersionVM*)&val;
                                     ^~~
./qtum/qtumtransaction.h:24:37: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
checkpointsync.cpp: In member function ‘bool CSyncCheckpoint::ProcessSyncCheckpoint(CNode*)’:
checkpointsync.cpp:342:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
     if (!ValidateSyncCheckpoint(hashCheckpoint))
     ^~
checkpointsync.cpp:345:2: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
  CBlockIndex* pindexCheckpoint = mapBlockIndex[hashCheckpoint];
  ^~~~~~~~~~~
checkpointsync.cpp:345:15: warning: unused variable ‘pindexCheckpoint’ [-Wunused-variable]
  CBlockIndex* pindexCheckpoint = mapBlockIndex[hashCheckpoint];
               ^~~~~~~~~~~~~~~~
  CXX      libbitcoin_server_a-httpserver.o
  CXX      libbitcoin_server_a-init.o
In file included from ./qtum/qtumstate.h:9:0,
                 from validation.h:37,
                 from init.cpp:23:
./qtum/qtumtransaction.h: In static member function ‘static VersionVM VersionVM::fromRaw(uint32_t)’:
./qtum/qtumtransaction.h:24:37: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
         VersionVM x = *(VersionVM*)&val;
                                     ^~~
./qtum/qtumtransaction.h:24:37: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  CXX      libbitcoin_server_a-dbwrapper.o
  CXX      libbitcoin_server_a-merkleblock.o
  CXX      libbitcoin_server_a-miner.o
In file included from ./qtum/qtumstate.h:9:0,
                 from ./validation.h:37,
                 from miner.h:17,
                 from miner.cpp:6:
./qtum/qtumtransaction.h: In static member function ‘static VersionVM VersionVM::fromRaw(uint32_t)’:
./qtum/qtumtransaction.h:24:37: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
         VersionVM x = *(VersionVM*)&val;
                                     ^~~
./qtum/qtumtransaction.h:24:37: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  CXX      libbitcoin_server_a-net.o
  CXX      libbitcoin_server_a-net_processing.o
In file included from ./qtum/qtumstate.h:9:0,
                 from validation.h:37,
                 from net_processing.cpp:17:
./qtum/qtumtransaction.h: In static member function ‘static VersionVM VersionVM::fromRaw(uint32_t)’:
./qtum/qtumtransaction.h:24:37: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
         VersionVM x = *(VersionVM*)&val;
                                     ^~~
./qtum/qtumtransaction.h:24:37: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  CXX      libbitcoin_server_a-noui.o
  CXX      libbitcoin_server_a-pow.o
  CXX      libbitcoin_server_a-pos.o
In file included from ./qtum/qtumstate.h:9:0,
                 from ./validation.h:37,
                 from txdb.h:20,
                 from pos.h:10,
                 from pos.cpp:8:
./qtum/qtumtransaction.h: In static member function ‘static VersionVM VersionVM::fromRaw(uint32_t)’:
./qtum/qtumtransaction.h:24:37: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
         VersionVM x = *(VersionVM*)&val;
                                     ^~~
./qtum/qtumtransaction.h:24:37: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  CXX      libbitcoin_server_a-rest.o
In file included from ./qtum/qtumstate.h:9:0,
                 from validation.h:37,
                 from rest.cpp:10:
./qtum/qtumtransaction.h: In static member function ‘static VersionVM VersionVM::fromRaw(uint32_t)’:
./qtum/qtumtransaction.h:24:37: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
         VersionVM x = *(VersionVM*)&val;
                                     ^~~
./qtum/qtumtransaction.h:24:37: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  CXX      script/libbitcoin_server_a-sigcache.o
  CXX      script/libbitcoin_server_a-ismine.o
  CXX      libbitcoin_server_a-timedata.o
  CXX      libbitcoin_server_a-torcontrol.o
  CXX      libbitcoin_server_a-txdb.o
In file included from ./qtum/qtumstate.h:9:0,
                 from ./validation.h:37,
                 from txdb.h:20,
                 from txdb.cpp:6:
./qtum/qtumtransaction.h: In static member function ‘static VersionVM VersionVM::fromRaw(uint32_t)’:
./qtum/qtumtransaction.h:24:37: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
         VersionVM x = *(VersionVM*)&val;
                                     ^~~
./qtum/qtumtransaction.h:24:37: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  CXX      libbitcoin_server_a-txmempool.o
  CXX      libbitcoin_server_a-ui_interface.o
In file included from ./qtum/qtumstate.h:9:0,
                 from validation.h:37,
                 from txmempool.cpp:11:
./qtum/qtumtransaction.h: In static member function ‘static VersionVM VersionVM::fromRaw(uint32_t)’:
./qtum/qtumtransaction.h:24:37: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
         VersionVM x = *(VersionVM*)&val;
                                     ^~~
./qtum/qtumtransaction.h:24:37: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
  CXX      libbitcoin_server_a-validation.o
In file included from ./qtum/qtumstate.h:9:0,
                 from validation.h:37,
                 from validation.cpp:6:
./qtum/qtumtransaction.h: In static member function ‘static VersionVM VersionVM::fromRaw(uint32_t)’:
./qtum/qtumtransaction.h:24:37: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
         VersionVM x = *(VersionVM*)&val;
                                     ^~~
./qtum/qtumtransaction.h:24:37: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
validation.cpp: In function ‘bool ContextualCheckBlockHeader(const CBlockHeader&, CValidationState&, const Consensus::Params&, const CBlockIndex*, int64_t)’:
validation.cpp:4124:15: warning: unused variable ‘nHeight’ [-Wunused-variable]
     const int nHeight = pindexPrev == NULL ? 0 : pindexPrev->nHeight + 1;
               ^~~~~~~
  CXX      libbitcoin_server_a-validationinterface.o
  CXX      libbitcoin_server_a-versionbits.o
  CXX      consensus/libbitcoin_server_a-consensus.o
  CXX      qtum/libbitcoin_server_a-storageresults.o
  CXX      libbitcoin_common_a-amount.o
  CXX      libbitcoin_common_a-base58.o
  CXX      libbitcoin_common_a-chainparams.o
  CXX      libbitcoin_common_a-coins.o
  CXX      libbitcoin_common_a-compressor.o
  CXX      libbitcoin_common_a-core_read.o
  CXX      libbitcoin_common_a-core_write.o
  CXX      libbitcoin_common_a-key.o
key.cpp: In function ‘bool EnsureLowS(std::vector<unsigned char>&)’:
key.cpp:149:19: error: invalid use of incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
     if (BN_cmp(sig->s, halforder) > 0) {
                   ^~
In file included from /usr/include/openssl/ecdsa.h:10:0,
                 from key.cpp:17:
/usr/include/openssl/ec.h:1039:16: note: forward declaration of ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
 typedef struct ECDSA_SIG_st ECDSA_SIG;
                ^~~~~~~~~~~~
key.cpp:151:19: error: invalid use of incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
         BN_sub(sig->s, order, sig->s);
                   ^~
In file included from /usr/include/openssl/ecdsa.h:10:0,
                 from key.cpp:17:
/usr/include/openssl/ec.h:1039:16: note: forward declaration of ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
 typedef struct ECDSA_SIG_st ECDSA_SIG;
                ^~~~~~~~~~~~
key.cpp:151:34: error: invalid use of incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
         BN_sub(sig->s, order, sig->s);
                                  ^~
In file included from /usr/include/openssl/ecdsa.h:10:0,
                 from key.cpp:17:
/usr/include/openssl/ec.h:1039:16: note: forward declaration of ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
 typedef struct ECDSA_SIG_st ECDSA_SIG;
                ^~~~~~~~~~~~
Makefile:7642: recipe for target 'libbitcoin_common_a-key.o' failed
make[2]: *** [libbitcoin_common_a-key.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/myhome/Documents/HTMLCOIN/src'
Makefile:13710: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/myhome/Documents/HTMLCOIN/src'
Makefile:693: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by Bushstar** [comment]
Do not build with system libs, use the depends folder, presuming 64-bit Linux.

```
git clean -fdx
cd depends
make HOST=x86_64-pc-linux-gnu
cd ..
rm -Rf src/cpp-ethereum/
git submodule update --init --recursive
./autogen.sh
./configure --prefix=`pwd`/depends/x86_64-pc-linux-gnu --disable-tests --disable-bench --enable-static --disable-shared
make
```

**Comment by syndrael** [comment]
Long time compilation, many many warnig, but htmlcoind seems working..
Thx a lot.
