### ISSUE TITLE
staking weight incorrect

### ISSUE THREAD

**Issue by amfcoin** [HTMLCOIN/HTMLCOIN#5]
This issue tracker is only for technical issues related to Qtum.

### Expected behaviour
The staking weight should be the total amount of coins

### Actual behaviour
the staking weight uses only one of the receivingadresses

### What version of Qtum are you using?
2.0.0.2

### Machine specs:
- OS: macOS
- CPU:
- RAM:
- Disk size:

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by amfcoin** [comment]
Problem has been solved, it takes a while but then synchronizes to correct amount

**Comment by richardjoo** [comment]
do we need to upgrade the wallet to see the fix?

**Comment by Bushstar** [comment]
An update to the client would be required.
