### ISSUE TITLE
mined block disappeared ?

### ISSUE THREAD

**Issue by jzahraoui** [HTMLCOIN/HTMLCOIN#50]
Hello,

I'm mining in solo with GPU. everything goes well until I saw the wallet notify me for find a new block but when I open the wallet there is not trace of the transaction.
strange ???
I opened the log file, found the submitted block section, took the hash then verify it into https://html.mastercalls.io/search
not any single trace of this transaction.

my wallet was locked when I was mining but normally it don't have to be unlocked right ?

want to attach log but don't know if it's safe or if I have to remove some informations ?

your help will be very appreciated.

PS : sorry for my bad english :)

**Comment by lunamonkey** [comment]
This can happen if someone else mined the same block at the same time and their confirmation beat you to consensus.

**Comment by Bushstar** [comment]
It is safe to attach the debug.log from your client and/or miner.

Mined blocks do sometimes get orphaned when a competing block at the same height as yours gets another block added to it before yours does making their block part of the longer chain.

**Comment by jzahraoui** [comment]
what your are saying guys is that I'm in very bad luck...
I think it's harder to do that than finding a block right ?
It should be a reward for that :))
here is the log by the way, I removed some informations.
[htmlcoin_debug.log](https://github.com/HTMLCOIN/HTMLCOIN/files/1808366/htmlcoin_debug.log)

**Comment by sunk818** [comment]
I wonder if you are fully synced with block gain. Normally, it should be 0.999 for progress. If you are not correct height mined block will never be accepted.

**Comment by Bushstar** [comment]
Looking at the log explains it, you found block 160825, 5 seconds someone released blocks 160825 and 160826 on to the network making yours an orphan. This is probably not an accident but someone mining "greedily", it is pretty typical of those with greater hash power than the majority.

**Comment by jzahraoui** [comment]
thank you very much for your help.
I have a better understanding now.
It's not an issue, but it was the first time I'm facing this situation.
by the way I believe in this this coin and I gone continue to mine it no matter what even with my ridiculous hashrate. :)

**Comment by sunk818** [comment]
@bushstar so having more difficult hash doesn't give you the reward? Two blocks always win out one block?

**Comment by Bushstar** [comment]
The longest chain has the most work and will become the main chain over a shorter chain, that's how clients choose between different chains. A longer chain will win over a shorter chain.
