### ISSUE TITLE
sendmany??

### ISSUE THREAD

**Issue by yatson1** [HTMLCOIN/HTMLCOIN#51]
What does it mean? I'm making a transaction
sendmany "" "{\" HkVGfRexCF88AwQ2YJ2bSvT4ggv4FNFeBi \ ": 6590.09725277}"

in the block browser:
https://html.mastercalls.io/tx/a1bb4aee35d45751233e574a4e37f4e8af7f2253c60f03e65e71d9910d1b11d7

Where did the second deal come from? 410.01231523?

in wallet
15/15/18 23:25 Confirmed (14 confirmations). Sent (no label) HiwwDbZVBSHDVVetERvDoJscsVGYumCQgQ -410.01617923

what does it mean?

**Comment by Bushstar** [comment]
Your inputs totalled more than the outputs. You cannot spent part of a UTXO but have to spend all of it, so your wallet creates a change address in the local wallet to send the remaining funds to. If you have a GUI enable coin control and look at the inputs window on the send tab or in the console dump the private key for the change address to prove that you own it.

**Comment by yatson1** [comment]
Thank you! understood.

**Comment by adamscope** [comment]
If i checked "dont use change address", But left spend unconfirmed change checked, would I lose html if the inputs where greater than the outputs?  Am I at risk of loosing "burning" html if I check "don't use change address".
