### ISSUE TITLE
Wallet not connecting to peers and not synchronizing

### ISSUE THREAD

**Issue by RaedNahal** [HTMLCOIN/HTMLCOIN#55]
The HTMLCoin wallet 5.7.1 is not connecting to peers. There are 0 active connections to the HTMLCoin network. I have no firewall . 

Screenshots.
![capture](https://user-images.githubusercontent.com/11636487/40250290-803e44b6-5ade-11e8-83ad-4c4cc1244bbd.JPG)

Machine specs:
- OS: Win7 64bit
- CPU: 2.4 Intel i3
- RAM: 8GB
- Disk size: 500GB

**Comment by leandrogomesmachado** [comment]
Just update your wallet to the last version (actual version is 2.1) and will work fine.
