### ISSUE TITLE
Cooperation with Chinese website

### ISSUE THREAD

**Issue by huang2287832** [HTMLCOIN/HTMLCOIN#6]
if this project can Cooperation with Chinese website,
and it will be good for your project development,Active community
for example:
https://www.aex.com/
https://www.binance.com/
https://gate.io/
https://www.okex.com/
...
I think they are so pleasure to Cooperation with foreign project, especially html, 
because html is heat is China, I'm an engineer for erlang, java, python and html

**Comment by HTMLCOIN** [comment]
Hi,

How do you want to collaborate?

All the best,



Amando Boncales, BA, MSEd, MA, PhDc.
Chief Executive Officer
Htmlcoin Foundation
Chicago, IL 60601

dev@htmlcoin.team
815-981-1100 <(815)%20981-1100>
https://www.linkedin.com/in/amando-boncales/



Telegram <https://t.me/htmlcoinofficial>   I   Twitter
<https://twitter.com/HTMLCOIN>   I   Reddit
<https://www.reddit.com/r/htmlcoin_community/>   I   Slack
<https://join.slack.com/t/htmlcoin/shared_invite/MjI2NDY2NDMxNDc0LTE1MDI3Mzg5NjctY2JkNDIyZjdlMw>
  I   Bitcointalk <https://bitcointalk.org/index.php?topic=801489.0;all>
I   Facebook <https://www.facebook.com/groups/htmlcoin/>  I
CryptocurrencyTalk <https://cryptocurrencytalk.com/topic/17467-htmlcoin/>
