### ISSUE TITLE
2.1.0.0 Not starting minimized

### ISSUE THREAD

**Issue by mbootsman** [HTMLCOIN/HTMLCOIN#60]
When launching the HTMLCOIN wallet with `/home/xxxx/Apps/HTML/htmlcoin-qt -min`, the wallet does not start minimized.

### Can you reliably reproduce the issue?
Yes
1. Exit HTMLCOIN wallet.
2. Launch with command `/home/xxxx/Apps/HTML/htmlcoin-qt -min`
3. Wallet is launched in normal window

### Expected behaviour
Wallet should start minimized.

### Actual behaviour
Wallet launched in normal window.

### What version of HTMLCOIN are you using?
Using the linux x64 package `htmlcoin-2.1.0-linux64.tar.gz`

### Machine specs:
- OS: Ubuntu 18.04 LTS

**Comment by fogoat** [comment]
@mbootsman this appears to be an upstream request from Bitcoin even as recently as Oct 2018: https://github.com/bitcoin/bitcoin/issues/14550

In your HTMLCOIN, edit your htmlcoin.conf so it has the entry 

`min=1`

I verified in macOS 10.12.6, HTMLCOIN 2.3.1 that wallet starts minimized. Can you test on your platform as well? If it works on Ubuntu 18 LTS, please close this issue.
