### ISSUE TITLE
Link needs updating: https://ethereum.github.io/ is deprecated (Desktop Wallet / Smart Contracts)

### ISSUE THREAD

**Issue by gruvin** [HTMLCOIN/HTMLCOIN#61]
### Describe the issue

Technically :p ...
... the link labelled, _Solidity compiler_, as found on the desktop wallet's, _Smart Contracts / Create_ page is out of date.

The Solidity Remix IDE has moved **from** https://ethereum.github.io/ **to** https://remix.ethereum.org/

The current github version link shows a warning dialog, as attached.

### Screenshots.
<img width="239" alt="screen shot 2018-07-23 at 2 21 48 pm" src="https://user-images.githubusercontent.com/7283745/43054235-ad78ea38-8e84-11e8-92ef-c50d91a9c5c2.png">
<img width="667" alt="screen shot 2018-07-23 at 2 21 14 pm" src="https://user-images.githubusercontent.com/7283745/43054248-bbf296fe-8e84-11e8-91dc-03fef6a958d8.png">

### What version of HTMLCOIN are you using?
HTMLCOIN CORE version 2.1.0.0 (64-bit) RELEASE

### Machine specs:
- OS: Ubuntu Desktop 16.04

**Comment by Bushstar** [comment]
Link has been updated in the following commit.

https://github.com/HTMLCOIN/HTMLCOIN/commit/6ebd5feba25cc4bd7b1992840680a718a92b3088
