### ISSUE TITLE
HTML 2.1: UI, Icon, QRC icon should say HRC

### ISSUE THREAD

**Issue by fogoat** [HTMLCOIN/HTMLCOIN#64]
From @coblassa Telegram user:

I think 'QRC' is the wrong word and 'HRC' is the correct word.

https://github.com/HTMLCOIN/HTMLCOIN/blob/master-2.1/src/qt/res/icons/qrctoken.png

![qrc-vs-hrc](https://user-images.githubusercontent.com/6989799/43114084-0d3fa1dc-8eb2-11e8-8790-5cf7918a21e2.jpg)

**Comment by Bushstar** [comment]
This is now fixed in the 2.2.0 release, thanks for the report, it did not go unnoticed.
