### ISSUE TITLE
2.1.1.0 gas estimation not working

### ISSUE THREAD

**Issue by gruvin** [HTMLCOIN/HTMLCOIN#69]
### Describe the issue

Neither HTMLCOIN or HRC Token sends seem to do any successful gas estimation. Even changing the, "Confirmation time target" field makes no change to the gas price displayed. The following four images show examples ...

#### HTMLCOIN Send
![2-blocks](https://user-images.githubusercontent.com/7283745/43754422-ec82ea72-9a5e-11e8-895c-87e325a91a4a.png)
![12-blocks](https://user-images.githubusercontent.com/7283745/43754424-ee231ff0-9a5e-11e8-9745-bbaeea4669dd.png)
![custom](https://user-images.githubusercontent.com/7283745/43754429-efc96c06-9a5e-11e8-965d-915295a3fa23.png)

#### HRC Token Send
![token-send](https://user-images.githubusercontent.com/7283745/43754432-f10cdada-9a5e-11e8-9c5c-280b148da15e.png)

### Can you reliably reproduce the issue?
Yes. Simply replicate the images, above.

### Expected behaviour
Gas price estimation based on recent network mempool activity -- or however that is supposed to work.

### Actual behaviour
As above -- estimations are not working.

### What version of HTMLCOIN are you using?
2.1.1.0 

### Machine specs:
- OS: Ubuntu 16.04 (xfce4)
- CPU: AMD
- RAM: 16GB
- Disk size: 256GB
- Disk Type (HD/SDD): SSD

### Any extra information that might be useful in the debugging process.
From `debug.log` ...

```
2018-08-07 04:33:33 FeeEst: 1 >60% decay 0.96200: feerate: -1 from (-1 - -1) -nan% 0.0/(0.0 0 mem 0.0 out) Fail: (0 - 1e+99) 0.13% 0.0/(0.0 0 mem 0.0 out)
2018-08-07 04:33:33 FeeEst: 2 >85% decay 0.96200: feerate: -1 from (-1 - -1) -nan% 0.0/(0.0 0 mem 0.0 out) Fail: (0 - 1e+99) 100.00% 0.0/(0.0 0 mem 0.0 out)
2018-08-07 04:33:33 FeeEst: 4 >95% decay 0.96200: feerate: -1 from (-1 - -1) -nan% 0.0/(0.0 0 mem 0.0 out) Fail: (0 - 1e+99) 100.00% 0.0/(0.0 0 mem 0.0 out)
2018-08-07 04:33:33 FeeEst: 4 >95% decay 0.99520: feerate: -1 from (-1 - -1) -nan% 0.0/(0.0 0 mem 0.0 out) Fail: (0 - 1e+99) 100.00% 2.1/(2.1 0 mem 0.0 out)
2018-08-07 04:33:33 FeeEst: 4 >95% decay 0.99931: feerate: -1 from (-1 - -1) -nan% 0.0/(0.0 0 mem 0.0 out) Fail: (0 - 1e+99) 100.00% 56.8/(56.8 0 mem 0.0 out)
```

```
$ cat .htmlcoin/htmlcoin.conf 
server=1
whitelist=127.0.0.1

rpcallowip=127.0.0.1
rpcallowip=192.168.1.0/24
rpcuser=user
rpcpassword=password
rpcport=18332

txindex=1
addressindex=1
timestampindex=1
spentindex=1
gen=0

zmqpubrawtx=tcp://127.0.0.1:28332
zmqpubhashblock=tcp://127.0.0.1:28332

addrindex=1
logevents=1
debug=0
```

**Comment by gruvin** [comment]
I note also that `-paytxfee=n` is either ignored or simply not displayed where, `0.00400000` otherwise is. (I have not performed an actual transaction with this setting employed.)

The acceptable values for `-paytxfee` (those that do not produce errors or warnings) seem odd, too. Like, the minimum allowable value is `0.00400000`HTML/Kb ... even though 0.002HTML in fact seems to work just fine (gets mined within a couple blocks.)

**Comment by Bushstar** [comment]
This is more a feature for Bitcoin where blocks are full, as HTMLCOIN blocks are empty you would expect TXs to mint in a couple of blocks regardless of whether the fee was high or not so the recommended fee stays on the DEFAULT_TRANSACTION_MINFEE value.

**Comment by gruvin** [comment]
On Wed, 8 Aug 2018 at 18:07, Peter Bushnell <notifications@github.com>
wrote:

> This is more a feature for Bitcoin where blocks are full, as HTMLCOIN
> blocks are empty you would expect TXs to mint in a couple of blocks
> regardless of whether the fee was high or not so the recommended fee stays
> on the DEFAULT_TRANSACTION_MINFEE value.

Oh, right. This is a staking coin. Of course. Duh. HOWEVER ...

For HRC tokens, the gas price default is so low in fact, that my transactions are NEVER mined. As a result, I still have two week old transactions not confirmed.

The default gas price for HRC tokens in my HTMLCOIN wallet UI is 0.00000040 HTML -- per KB, I presume? It doesn't say on the screen, like it does for HTML transactions. Even if it's per byte, that's still a 10th the usual HTML price. (Count the decimals.)

So, I have to keep manually changing the gas fee for HRC token transactions, to at least 0.002HTML, as found by experimentation. That setting doesn't stick, making it a real pain.

All this leads me to wonder, "Who is the bad player in the system?" Is it the wallet for setting HRC gas too low --or-- stakers, "refusing" to mine HRC transactions at that low fee? Which was the developers' intention? Can't both be right. 😝

The normal HTML price is of course, 0.004HTML per KB.  That's fine for HTML transactions, although 0.002 seems to work just as well. {shrug}

**Comment by gruvin** [comment]
sigh
