### ISSUE TITLE
Linux mining limits

### ISSUE THREAD

**Issue by allardheld** [HTMLCOIN/HTMLCOIN#7]
Hi,

Appreciate all the work you guys are doing for HTMLCOIN! I'm mining with an Ubuntu setup and the html deamon but no matter how many sessions I start, it only uses 4 cores max (32 total)

Also, the sessions break after running more than 20 concurrent sessions.
Thanks

Allard

**Comment by sunk818** [comment]
I noticed four core is the max. 400% CPU is the max.

**Comment by Bushstar** [comment]
As an external miner is slow coming a better internal miner is something that I can work on, when you can set it to keep mining and allow you to set the thread count. When I get the time I'll get on to this but I'm stretched very thinly at the moment, not taken any days off now for months. This is on my to-do list.

**Comment by allardheld** [comment]
Thanks for the quick reply. I'm using htmlcoin-sli, not an external miner or am I mistaken?
Keep up the good work! 👍

**Comment by Bushstar** [comment]
External miner is slow coming in that it does not yet exist and I've not been able to pin down a miner developer. Internal mining only at the moment.
