### ISSUE TITLE
HTMLCOIN wallet 2.3.1 not connecting to peers and not synchronising

### ISSUE THREAD

**Issue by Collector18121971** [HTMLCOIN/HTMLCOIN#74]
Hello,

After updating to the latest HTMLCOIN Wallet 2.3.1. my wallet is not connecting anymore. I have 0 active connections

I have tried to reinstal the wallet and restore my wallet with a backup wallet (dat file) but no result.

Can you please help?

**Comment by Bushstar** [comment]
Open the Debug window from the Help menu and go to the Peers tab, make sure you do not have any banned peers there. You can try to manually add peers from the list below, click on node list to get IP addresses. On the Console tab of the Debug window using the following replacing IP with the IP from node list.

addnode IP add

https://chainz.cryptoid.info/html/#!network

**Comment by Collector18121971** [comment]
Thank you, indeed there some banned peers and I have debokked them and have 5 active connections now. However, the blockchain still does not work and displays 'connceting to peers'. It still is 15 hours posthoned no. The last block processed is 633626 (yesterday evening) . Also, I made a testtrader to a external exhange. It was subtracted from my wallet (and several times confirmed) as displayed in my wallet, but was not received by the external exchange untill now

**Comment by Collector18121971** [comment]
It still does not synchronise

**Comment by Collector18121971** [comment]
Updated: after the 15 minutes the active connections are banned again and I have again no active connections

**Comment by Bushstar** [comment]
Can you give me the output from the following command in the console?

getblockhash 633626

**Comment by Bushstar** [comment]
Also add the following to your htmlcoin.conf file in your data directory, if you do not have one then please create it.

addnode=106.246.54.75
addnode=107.175.148.196
addnode=108.168.30.122
addnode=108.199.184.54
addnode=109.67.241.73
addnode=114.29.52.206

**Comment by Collector18121971** [comment]
getblockhash 633626:

 Block height out of range (code -8)
-

**Comment by Collector18121971** [comment]
How and were do I add the mentioned above to the htmlcoin.conf file?

**Comment by Collector18121971** [comment]
I see now that the last block was 633323 (instead of 633626 what I typed above)
 
The answer to getblockhash 633323 is: 

  | 0000000000a92c61333486bb79e91af4e521c7cc5c1a3e0a3abfcf5bc30ebde5
-- | --

**Comment by Collector18121971** [comment]
I find the htmlcoin.conf How do I add the data above?

**Comment by Bushstar** [comment]
That block hash is from the other pre-fork client chain, you will not be able to connect to others on the new chain until you remove old chain data and resync. Go to your HTMLCOIN data directory and delete everything except your wallet.dat and or the wallets directory. Then start the client again, it will sync from the genesis block and this time will not get stuck along the way.

**Comment by ravibhojwani** [comment]
So kindly what is the best Stable release as I’m keen to reinstall

**Comment by Bushstar** [comment]
You can find the stable releases on the page below, the top one is the latest which is currently 2.3.1.

https://github.com/HTMLCOIN/HTMLCOIN/releases

**Comment by Collector18121971** [comment]
Hello,

I have performed your actions a you described. However:

My saldo was: 5,9 mln HTMLCOIN. This is the correct saldo I have.
My saldo now based on your actions is 4.2 mln as displayed in wallet 2.3.1.

I am missing 1.7 mln HTMLCOINS

Please your help

**Comment by Collector18121971** [comment]
additonally: If I calculated the transactions manually I count my 5.9 mln coins but it is not the total / sum displayed in the wallet

**Comment by fogoat** [comment]
@Collector18121971 You can try `zapwallettxes=1` from the command line one time to see if you can recover the missing txes.

**Comment by Collector18121971** [comment]
Any ideas how this can or what I can do to fixe this:

The transactions seperatly counts to my orignal balances of 5.9 mln but the displayed balance is 1.9 mln HTMLCOINS to low

**Comment by Bushstar** [comment]
Is your client now synced with the network to the block height and hash shown on the explorer here?

http://explorer.htmlcoin.com

As sunk818 suggests try starting the client with the following, you can add the line to your htmlcoin.conf file in your HTMLCOIN data directory.

zapwallettxes=2

**Comment by Collector18121971** [comment]
Ok thanks. How can I acces and adjust the hmlcoin.conf file? What actions do I have to take?

Can you help me with that please?

Many thanks

**Comment by Bushstar** [comment]
Presuming you are on Windows. Go to Start -> Run (or press WinKey+R) and run this:

%APPDATA%\HTMLCOIN

In the folder that opens create a htmlcoin.conf file, like an empty Notepad file. You may want to create the file in Notepad, save it locally and copy it to the data directory. Add the line below to the file using Notepad, save and then start the client. If done correctly the client should take several minutes to start while it rescans the chain.

zapwallettxes=2

There's further instructions for creating this file for Bitcoin which is easily adaptable for HTMLCOIN.

https://en.bitcoin.it/wiki/Running_Bitcoin#Bitcoin.conf_Configuration_File

**Comment by Collector18121971** [comment]
Hello,

The blockchain is synchronised to latest block (good news)

However, my balance is still 1.4 mln to low. The seperate transactions I see in the client sums to the orginal amount but it is wronly displayed as a total.

I tried to command above (zapwallettxes=2 in de conf file)  but without any result.

Can you help me further?

**Comment by Bushstar** [comment]
I do wonder if your htmlcoin.conf is correct, in Windows the file type is hidden so a htmlcoin.conf file can actually be a htmlcoin.conf.txt file which will not work.

However we have had others in the exact same situation as yourself, upgrading after the fork with blocks from the wrong chain and also have found coins to be "locked" out from the balance. The fix that has been found to work is to start HTMLCOIN with the salvagewallet options.

Find the HTMLCOIN shortcut in your file system, right click it and select properties, add -salvagewallet to the end of the target field as shown in the image below. Start the wallet, it will recover private keys from your wallet.dat and create a new wallet.dat with them. Remember to remove the -salvagewallet option afterwards.

![image](https://user-images.githubusercontent.com/5293433/52778451-f3a00680-303d-11e9-87f8-e7f7a2f85542.png)

**Comment by Collector18121971** [comment]
Hello, thank you. I do not have the tab shortcut to change the row target.  The other tabs I have but can not change the above row.

I have windows 10.

**Comment by Bushstar** [comment]
That screenshot is from Windows 10. In the Start Menu find the HTMLCOIN shortcut, right click and select "Open file location", this will open the folder where the shortcut is location on the hard drive. Like in the screenshot below, then right click the HTMLCOIN shortcut and select properties to get to the shortcut properties shown in the above screenshot.

![image](https://user-images.githubusercontent.com/5293433/52779916-0700a100-3041-11e9-8d86-2dcd391d2f62.png)

**Comment by Collector18121971** [comment]
Thank you, I get the mentioned screen only I do not get the tab 'shortcut' to adjust the path. See the picture below:

![image](https://user-images.githubusercontent.com/47590637/52786823-353faa00-305c-11e9-87a9-777db29a569b.png)

**Comment by Collector18121971** [comment]
So I can not change the path

**Comment by Bushstar** [comment]
There's another way to do this by starting htmlcoin-qt.exe via the command line.

Press Windows Key + R to open the Run dialog as shown below.

![image](https://user-images.githubusercontent.com/5293433/52789676-6c15c000-305c-11e9-9ad9-757e48efaf1b.png)

Type in cmd and press OK. The following window should open.

![image](https://user-images.githubusercontent.com/5293433/52789698-7fc12680-305c-11e9-8bf0-197244d7bafe.png)

Type in the following and press enter to change directory to your HTMLCOIN2 folder.

`cd "C:\Program Files (x86)\HTMLCOIN2"`

You should see that the path in the cmd window has changed to the HTMLCOIN2 folder as shown in the screenshot below.

![image](https://user-images.githubusercontent.com/5293433/52789775-bf880e00-305c-11e9-95e2-dee9d3e70d2e.png)

Now type in the following and press enter to start HTMLCOIN with the salvage wallet option.

`htmlcoin-qt.exe -salvagewallet`

After it has rebuilt your wallet and rescanned the blockchain your balance should be restored.

**Comment by Collector18121971** [comment]
Super, it work! My balance is correct now. Many thanks!

Do I have to adjust something back again or can I just close my wallet?

**Comment by Bushstar** [comment]
Good news. Close the wallet and use it as normal.

**Comment by silasechegini** [comment]
I will appreciate the assistance of whoever can help, please.
I upgraded from htmlcoin-2.0.2.1-win32 (beta) to htmlcoin-2.5.0-win32 and since then I have had the following issues.
1. The wallet will not sync with the network ... it is stuck at 91.4% for over a week now.

2. no connection to peers on the HTML network

**I have one the following to help the situation:**
1. I unbanned all the banned peers and there was connection to over 10 peers on the network but the headers still don't sync past 91.4% although I still had the accurate balance of my wallet.

2. the last block I received was 1008527 so I ran getblockhash 1008527 and the result was ee75d30ed88f67270a415a3112705088e8c4c7f00c6631d8629975a9d6ffc2c2

3. I took backups weekly of my wallet before the upgrade so I installed the new wallet and then removed everything in the appdata/roaming/html folder except the wallet.dat file and the peers' file, and then restarted the wallet. the wallet syncs and connects to oven 10 peers but the balance of my wallet has been at 0 since then.

4. I deleted the entire content of the appdata/roaming/html folder and then got the wallet to sync afresh, then I restored the wallet from File->restore wallet and the wallet balance was still 0 even though there was a connection to peers on the network and the headers synced up correctly.

not sure what else to do from here ... I am wondering if htmlcoin-2.5.0-win32 is the most stable version? or if there is something I am doing wrong.
