### ISSUE TITLE
HTMLCOIN CORE version v2.3.1.0 (64-bit) is not syncing

### ISSUE THREAD

**Issue by silveirabruno** [HTMLCOIN/HTMLCOIN#75]
My HTMLCOIN CORE version v2.3.0.0 (64-bit) has stoped syncing, than I updated to v2.3.1.0 but the problem persists.

I updated to the new mandatory wallet ( v2.3.0.0) on Feb. 13th, and started staking. 
It was working fine until I went to bed. The next day I woke up and it has stopped working (mined a block at 22:55 São Paulo timezone).
I updated to the new version (v2.3.1.0), but it's still not working.
It says it's not staking because I don't have mature coins... 

My config:
MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports)
3,1 GHz Intel Core i5
8 GB 2133 MHz LPDDR3
Macintosh HD
Intel Iris Plus Graphics 650 1536 MB
mac OS Mojave 10.14.3 (but has made no changes in it for the past few days)

Here is the print of the problem:
![print](https://user-images.githubusercontent.com/30032410/52982763-bed9d980-33c6-11e9-8a90-2d358e10ca6d.png)

Can anyone help?

Thanks a lot!
Bruno Silveira

**Comment by pianomanla** [comment]
I have the same issue, but at block 637483.  latest core version as well

**Comment by pianomanla** [comment]
<img width="774" alt="Screen Shot 2019-03-12 at 1 23 59 PM" src="https://user-images.githubusercontent.com/48491992/54225614-1c46df00-44ca-11e9-8c6c-417572d468e6.png">

**Comment by Bushstar** [comment]
Close the client, go to your data directory and delete everything except your wallet.dat and/or wallets folder. To find your data directory follow the advice from the page link below substituting HTMLCOIN for Bitcoin.

https://en.bitcoin.it/wiki/Data_directory

**Comment by pianomanla** [comment]
After following the above instructions, I have renown fully sync'd the blockchain to current, and all of my transactions are present in the Transactions list, but I have a zero balance in my wallet.  What do I do now?

**Comment by Bushstar** [comment]
In the HTMLCOIN data directory create a txt file called htmlcoin.conf add the following line.

zapwallettxes=2

Start the client, it will delete all transactions and rescan the blockchain to rebuild your transaction history and balance. Afterwards starting the client remove the above line from the conf file.

**Comment by pianomanla** [comment]
By doing so, will that also search for the transactions related to staking my coins?

**Comment by guncoin** [comment]
It will find all TXs related to the private keys in your wallet.dat, short answer, yes.

**Comment by Bushstar** [comment]
commented less than a minute ago
It will find all TXs related to the private keys in your wallet.dat, short answer, yes.

**Comment by pianomanla** [comment]
<img width="521" alt="Screen Shot 2019-03-13 at 9 39 29 AM" src="https://user-images.githubusercontent.com/48491992/54287582-e827f880-4573-11e9-925b-df7d701c7297.png">

I have had the file in the folder for a few hours now and there doesn't seem to be any progress... Approximately how long should the process take.  FYI, re-syncing the entire blockchain yesterday afternoon took about 35 minutes on my mac desktop.  

Thank you for your help in trying to resolve this issue!

**Comment by Bushstar** [comment]
That file will not work as it's a Rich Text Document, it needs to be a plaintext file. The application will take a while to start but once started it has completed the rescan.

**Comment by pianomanla** [comment]
<img width="612" alt="Screen Shot 2019-03-13 at 9 55 09 AM" src="https://user-images.githubusercontent.com/48491992/54288817-17d80000-4576-11e9-9b3c-983e774cb3ef.png">

Thank you for the clarification.  I have converted the file to plain text now and have relaunched the client.  All of the "previous recent transactions" remain in the "My Wallet" tab, and I have 8 network connections currently with last block sync'd being 670240...  At this point, do I simply allow it to run and see what happens, or should I unlock the wallet?

**Comment by Bushstar** [comment]
You are very close. One more error I just spotted, the file is named wrong, it should be htmlcoin.conf, yours is called htmlcoim.conf. You can use the file I've created and linked in below.

https://drive.google.com/uc?export=download&id=1HvJQPySUsY8M73GccjYY_4Y1WxdgXO16

**Comment by pianomanla** [comment]
Replaced my file with the one downloaded from your google drive:
<img width="613" alt="Screen Shot 2019-03-13 at 12 26 48 PM" src="https://user-images.githubusercontent.com/48491992/54300645-47ddce00-458b-11e9-8344-48a5ec6b342c.png">

relaunched Client and starting block was 670280.  Two hours later, last block is 670375.  Still zero balances in wallet.  Any suggestions?
<img width="1072" alt="Screen Shot 2019-03-13 at 12 28 20 PM" src="https://user-images.githubusercontent.com/48491992/54300740-7f4c7a80-458b-11e9-9476-32d8e91a783d.png">

**Comment by Bushstar** [comment]
The file in your screenshot is named htmlcoin.conf.txt, I'm not sure how the .txt got appended to the end.

Please remove the .txt at the end of the file name and restart the client.

To test I just downloaded the file from my Drive and there's no .txt added, if you drag and dropped it from your Downloads folder it should have been fine, if you opened it in an editor and saved it to location perhaps it added the suffix.

**Comment by pianomanla** [comment]
I deleted the addition .txt extension and relaunched the client.  how long should I wait to see any motion?

**Comment by Bushstar** [comment]
If it works it should have done so when the client opens on the screen, so quickly.

**Comment by pianomanla** [comment]
Then it did not work... starting block when I opened the client was 670403... now on block 670440
<img width="877" alt="Screen Shot 2019-03-13 at 1 33 13 PM" src="https://user-images.githubusercontent.com/48491992/54305073-8f1c8c80-4594-11e9-93b4-fd9033710160.png">

Any other suggestions?

**Comment by Bushstar** [comment]
By the way the option zapwallettxes will not make a difference to block height.

Looks like the client failed to start with zapwallettxes=2.

Please contact me directly via email using pbushnell@htmlcoin.team
