### ISSUE TITLE
Wallet crashes after updating to 2.4.0 when block is found

### ISSUE THREAD

**Issue by antoniusman** [HTMLCOIN/HTMLCOIN#78]
I'm using nvidea cards on windows 10 to mine htmlcoin. So, i've installed 2.4.0 above previous wallet version. All setting are the same. RPC works normally. But when the block is found and is being submitted to the wallet - the wallet crashes. Same result on 2 different computers.

**Comment by Bushstar** [comment]
Are you mining with getblocktemplate or getwork?

**Comment by antoniusman** [comment]
I'm using standard ccminer miner by https://github.com/mghtthr/ccminer
A guess there is no option to select getblocktemplate or getwork to be used...

**Comment by Bushstar** [comment]
Thanks for the report and the link. I'll get this resolved tomorrow.

**Comment by Bushstar** [comment]
Please use the 2.4.1 release which should resolve this issue.

https://github.com/HTMLCOIN/HTMLCOIN/releases/tag/v2.4.1

The fix was to not call KeepKey on an unused CReserveKey.

https://github.com/HTMLCOIN/HTMLCOIN/commit/9f0bf88e5004b9da7b215e7a1c55cfa3cdaa4b00

**Comment by antoniusman** [comment]
Peter, now it works! Thanks for your fast reaction!
