### ISSUE TITLE
HTMLCOIN CORE version v2.0.0.4-beta (64-bit) wont sync (MacOS version)

### ISSUE THREAD

**Issue by z3ptor** [HTMLCOIN/HTMLCOIN#79]
Hello,

Last time the wallet was synced was 02.02.2018 and now it won’t connect. I have read some threads about this but it didn’t help me much.

I have added some pictures in hope that I can provide the best info so that I can get help. Here you can see what is in every file when I open it.

What do I do to make this wallet sync again? Step by step.

<img width="894" alt="Screenshot 2020-05-27 at 16 18 15" src="https://user-images.githubusercontent.com/66019981/83032970-d1fe3f00-a036-11ea-9443-1b1ff8aec63d.png">

Thanks

**Comment by Bushstar** [comment]
That version will not sync. Install the latest version found on the release page linked below.

https://github.com/HTMLCOIN/HTMLCOIN/releases

**Comment by z3ptor** [comment]
Update done, this is the status atm

<img width="746" alt="Screenshot 2020-05-27 at 17 24 08" src="https://user-images.githubusercontent.com/66019981/83039899-f9f1a080-a03e-11ea-932e-a5fc034a83fd.png">
<img width="1080" alt="Screenshot 2020-05-27 at 17 24 35" src="https://user-images.githubusercontent.com/66019981/83039909-fc53fa80-a03e-11ea-97fd-f25c4f87f884.png">

**Comment by Bushstar** [comment]
Please close the client and delete everything in your data directory except for your wallet.dat file and wallets directory if present, do not worry if no wallets directory is present. The wallet.dat holds all your private keys for your address so keep it safe. After start the client again and it will resync.

In short your data directory should be at the following location.

~/Library/Application Support/HTMLCOIN/

**Comment by z3ptor** [comment]
I need to make sure I understand correctly before deleting anything. Sorry if these questions are stupid.

When you say delete everything in the "data directory" do you mean all the  files that you see in the pictures linked below? There is no "wallet.dat" here btw. 
So delete any of these files or?

**Comment by Bushstar** [comment]
No, delete all files in the location below except for your wallet.dat and wallets directory if present.

~/Library/Application Support/HTMLCOIN/

**Comment by Bushstar** [comment]
If you do not know how to open your library folder then please take a look at the following link that offers several solutions.

https://nektony.com/blog/how-to-get-to-library-on-mac

**Comment by z3ptor** [comment]
I restarted the computer to make sure now.

Yes I know how to get into it. Finder/go/computer/machHD/lib/app supp/-->

When i look in application supp i cant find any files on htmlcoin tho

**Comment by Bushstar** [comment]
That's the system Library folder and not the one where the HTMLCOIN directory is located. You need to go into the Library folder inside your user profile, please follow the instruction in the link below to access ~/Library, The tilde ~ refers to your user profile on Mac.

https://nektony.com/blog/how-to-get-to-library-on-mac

**Comment by z3ptor** [comment]
🤯😂

**Comment by z3ptor** [comment]
Found it. I moved wallet.dat out of the file here. Delete rest?

**Comment by z3ptor** [comment]
It started. Thanks a million for the help Bushstar🤩

**Comment by Bushstar** [comment]
Glad it is sorted. Now closing this issue.
