### ISSUE TITLE
Cannot compile on OSX

### ISSUE THREAD

**Issue by sahara108** [HTMLCOIN/HTMLCOIN#8]
Hi, is the README outdated? I tried to follow the instructions but get the error when trying to run "make"

> Undefined symbols for architecture x86_64:
  "_SHA512_Final", referenced from:
      HMAC_SHA512_Init(HMAC_SHA512_CTX*, void const*, unsigned long) in libbitcoinconsensus_la-hash.o
      HMAC_SHA512_Final(unsigned char*, HMAC_SHA512_CTX*) in libbitcoinconsensus_la-hash.o
     (maybe you meant: __Z17HMAC_SHA512_FinalPhP15HMAC_SHA512_CTX)
  "_SHA512_Init", referenced from:
      HMAC_SHA512_Init(HMAC_SHA512_CTX*, void const*, unsigned long) in libbitcoinconsensus_la-hash.o
     (maybe you meant: __Z16HMAC_SHA512_InitP15HMAC_SHA512_CTXPKvm)
  "_SHA512_Update", referenced from:
      HMAC_SHA512_Init(HMAC_SHA512_CTX*, void const*, unsigned long) in libbitcoinconsensus_la-hash.o
      HMAC_SHA512_Update(HMAC_SHA512_CTX*, void const*, unsigned long) in libbitcoinconsensus_la-hash.o
      HMAC_SHA512_Final(unsigned char*, HMAC_SHA512_CTX*) in libbitcoinconsensus_la-hash.o
     (maybe you meant: __Z18HMAC_SHA512_UpdateP15HMAC_SHA512_CTXPKvm)
ld: symbol(s) not found for architecture x86_64

Any suggestion?

**Comment by sahara108** [comment]
Hi, I solve the problem but it required some minor change to the generated Makefile

In the Makefile, search for `LDFLAGS`

> LDFLAGS =  -Wl,-headerpad_max_install_names -Wl,-dead_strip

It is not correct. It needs to link with a `libcrypto`. So I try to run `make` command as follow:

> make LDFLAGS="-Wl,-headerpad_max_install_names -Wl,-dead_strip -L/usr/local/ssl/lib -lcrypto"

Now it's compiling.

**Comment by sahara108** [comment]
@Bushstar I also get this error after the `lcrypto`

> In file included from miner.cpp:6:
In file included from ./miner.h:10:
In file included from ./txmempool.h:25:
In file included from /usr/local/include/boost/multi_index/ordered_index.hpp:17:
/usr/local/include/boost/multi_index/detail/ord_index_impl.hpp:1181:10: error: no matching function for call to object of type 'const key_compare' (aka 'const CompareModifiedEntry')
      if(comp_(key(v),key(y->value())))return false;

Do you have any idea about this?

**Comment by sahara108** [comment]
This is fixed with this pull request: https://github.com/BitzenyCoreDevelopers/bitzeny/commit/46ffbcd8f6b12e21bd617569e6a5a84f9119a443

**Comment by Bushstar** [comment]
I compiled on Mac OS X 10.10 using Macports build tools, compiled the dependencies from the depends subfolder and then compiled with the following configure options.

```
./configure --disable-shared --enable-static --prefix=`pwd`/depends/x86_64-apple-darwin11
```

**Comment by sahara108** [comment]
Ah ha, I didn't think about the `static` option. Then instruction in README.md is for dynamic library. Anyway I able to compile now with the fix in the previous pull request and the same fix for other functions in txmempool.cpp
