### ISSUE TITLE
2.5 not responding/updating

### ISSUE THREAD

**Issue by Y4nEaster** [HTMLCOIN/HTMLCOIN#81]

**Comment by Bushstar** [comment]
Please stop the client and then delete all files in the HTMLCOIN data directory except the wallet.dat and/or wallets folder if present, then start the client again. There's information linked below about locating the data directory on different platforms, the instructions are for Bitcoin, just replace HTMLCOIN for Bitcoin.

https://en.bitcoin.it/wiki/Data_directory

**Comment by Y4nEaster** [comment]
👍
