### ISSUE TITLE
It is not opening on OS 10.9

### ISSUE THREAD

**Issue by brunohcamargos** [HTMLCOIN/HTMLCOIN#82]
It is not opening on OS 10.9. I can not upgrade my OS to 10.10 because i se some sofwares that is not updated to 10.10.

And the 2.5 wallet version needs 10.10 OS.
![Captura de Tela 2020-07-19 às 20 37 41](https://user-images.githubusercontent.com/68520857/87889708-679bc680-ca09-11ea-9bf1-7ae1fa81de85.png)

**Comment by Bushstar** [comment]
It is not possible to run HTMLCOIN 2.5 on Mac OS 10.9, there is no workaround for this. By the way Apple's support for that OS ended in September 2016.
