### ISSUE TITLE
Wallet headers dont sync and when they sync i loose my wallet coins

### ISSUE THREAD

**Issue by silasechegini** [HTMLCOIN/HTMLCOIN#83]
I will appreciate the assistance of whoever can help, please.
I upgraded from htmlcoin-2.0.2.1-win32 (beta) to htmlcoin-2.5.0-win32 and since then I have had the following issues.
1. The wallet will not sync with the network ... it is stuck at 91.4% for over a week now.

2. no connection to peers on the HTML network

**I have one the following to help the situation:**
1. I unbanned all the banned peers and there was connection to over 10 peers on the network but the headers still don't sync past 91.4% although I still had the accurate balance of my wallet.

2. the last block I received was 1008527 so I ran getblockhash 1008527 and the result was ee75d30ed88f67270a415a3112705088e8c4c7f00c6631d8629975a9d6ffc2c2

3. I took backups weekly of my wallet before the upgrade so I installed the new wallet and then removed everything in the appdata/roaming/html folder except the wallet.dat file and the peers' file, and then restarted the wallet. the wallet syncs and connects to oven 10 peers but the balance of my wallet has been at 0 since then.

4. I deleted the entire content of the appdata/roaming/html folder and then got the wallet to sync afresh, then I restored the wallet from File->restore wallet and the wallet balance was still 0 even though there was a connection to peers on the network and the headers synced up correctly.

not sure what else to do from here ... I am wondering if htmlcoin-2.5.0-win32 is the most stable version? or if there is something I am doing wrong.

**Comment by Bushstar** [comment]
Manually restore your wallet.dat, copy it to the HTMLCOIN data directory, then start the client. Do you know an address for any of your coins? You can check the balance of that address on the explorer to make sure it has been seen on the network. Were your coins from solo mining and staking or where some of them purchased from an exchange?

https://chainz.cryptoid.info/html/

**Comment by silasechegini** [comment]
thank you @Bushstar for reaching out. 
so from the complaint I made above, I have already tried restoring the wallet.dat manually and I can't see any of my coins after doing that.
when I check the address of the last completed transaction, I see the initial amount which I staked in 2018. Everything mined since 2018 till now does not show. 
and, I have made all my coins since 2018 from solo mining and staking. the amount I staked in 2018 was from a purchase made online.

**Comment by Bushstar** [comment]
There have been several hard forks since HTMLCOIN 2.0.2.1, it sounds like you were on the pre-fork branch which is not part of the main chain.

**Comment by silasechegini** [comment]
hmmm .. does this mean bad news?

**Comment by sunk818** [comment]
> hmmm .. does this mean bad news?

If you were mining and staking easily, then it was too good to be true and never was. Difficulty ramped up after GPU miner, so it'd be extremely rare for an in-wallet miner via Proof of Work to get create an accepted candidate block on the main chain.

**Comment by Bushstar** [comment]
> hmmm .. does this mean bad news?

Yes. HTMLCOIN 2.0 has not been on the same chain as the rest of the network for years now.

**Comment by silasechegini** [comment]
Okay, realistically, what is my best bet at this point?
Am I losing all my coins ?

**Comment by Bushstar** [comment]
Coins staked on 2.0 since the hard fork in 2018 are lost. Start staking with 2.5 and keep an eye on new releases.

**Comment by silasechegini** [comment]
that's a hard blow. 
okay, when I search for my address online, I find the amount which I staked in 2018 as my current balance but I can't see it in my wallet. How do I resolve this piece?

**Comment by Bushstar** [comment]
Start the wallet with the following in htmlcoin.conf, this should be a plain text file in your data directory, create it if it does not exist. Make sure that the file extension is .conf and not .txt.

zapwallettxes=1

That will make the wallet delete all wallet transactions and then will scan the entire Blockchain for any transactions that belong to the private keys held in your wallet.dat. The splash screen should give some indication that it is rescanning the Blockchain, normally rescanning followed by a percentage complete. Remove that line from the conf file afterwards.

**Comment by sunk818** [comment]
> Start the wallet with the following in htmlcoin.conf, this should be a plain text file in your data directory, 
> create it if it does not exist. Make sure that the file extension is .conf and not .txt.

Will this really work? If he's already on the wrong chain, wouldn't he need to erase the chain and start over (e.g. delete everything in %appdata%\HTMLCOIN except wallet.dat and htmlcoin.conf) and first from scratch? Wouldn't `zapwallettxes=1` just rescan existing blocks, but not put him on the right chain? Maybe I misunderstand how `zapwallettxes=1` works on HTMLCOIN.

**Comment by Bushstar** [comment]
@sunk818 he's done that already. Deleted everything in the data directory and synced on 2.5. I'm hoping that the coins are locked in staking transactions, it's something worth trying. If there's nothing there we'll see if the wallet can dump the private key for the address they believe is in it.

**Comment by fogoat** [comment]
> @sunk818 he's done that already. Deleted everything in the data directory and synced on 2.5. I'm hoping that the coins are locked in staking transactions, it's something worth trying. If there's nothing there we'll see if the wallet can dump the private key for the address they believe is in it.

Right you are. `zapwallettxes=1` has worked for me too with missing txes, so hopefully it'll work for @silasechegini

**Comment by silasechegini** [comment]
> zapwallettxes=1

thanks again .... are you saying i should delete all the files in the data directory (except my wallet) before performing this process or I should just go ahead with the process leaving my data directory as is?

**Comment by Bushstar** [comment]
Leave the data directory as is.

**Comment by silasechegini** [comment]
so, I did as you had said and I was able to get back to the amount I originally staked in 2018.
thanks @Bushstar @sunk818  for all the help. Appreciated.
