### ISSUE TITLE
2.5 Does not open on Mac 10.10.5 Yosemite.

### ISSUE THREAD

**Issue by brunohcamargos** [HTMLCOIN/HTMLCOIN#84]
I am using 2.3 Today i install version 2.4 and it works. Now, i install 2.5 version. 
The app does not open. It starts to load and quickly close.

I have uninstall the 2.3 version and the 2.4 version to see if there is some conflict. But 2.5 remains not opening.

I am using a MAC on 10.10.5 Yosemite IOS.

**Comment by Bushstar** [comment]
Minimum required version of MacOS is 10.12 as of HTMLCOIN 2.5. The Ethereum codebase was upgraded in this release which raised the minimum required version of MacOS and similar issues on other operating systems.
