### ISSUE TITLE
Problem With Desktop Wallet

### ISSUE THREAD

**Issue by gamesdevhouse** [HTMLCOIN/HTMLCOIN#86]
i have trouble sending my htmlcoins to exchange (hitbtc ) even coins are deducted from my wallet but never receiving on exchange . i cant find any problem . 
![3](https://user-images.githubusercontent.com/87873560/126820426-582739b8-3a75-4d50-93dd-0d0a8e7b40d2.png)
![2](https://user-images.githubusercontent.com/87873560/126820432-2c54530f-e8d7-4162-9671-08ef0f0ae5d0.png)
![1](https://user-images.githubusercontent.com/87873560/126820437-0796c64d-64fc-4f47-b0c3-5e2b43967563.png)

Please Guide Anyone

**Comment by Bushstar** [comment]
Please post your transaction ID.

**Comment by gamesdevhouse** [comment]
Hi peter thank you for replying fast . there is problem with my wallet . my balance is not ok . 

My actual real balance was : 73593114 HTML

On my desktop wallet it shows now : 73 583 714 HTML 

But on my blockchain balance shown is different Kindly see this wallet : https://explorer.htmlcoin.com/address/Hb5kuqZafod3TQ34LX5esVaWQrKnDp5p52

Please help me fix this ☹  also . now wallet is stuck on SYNC every time I open .




Sent from Mail for Windows 10

**Comment by Bushstar** [comment]
Note that the explorer will only show a balance for a single address and not all address in your wallet like change addresses created when you send funds. The address you posted shows a single incoming TX depositing 8,939,500.8593872 which has not been spent. This does not match either figure you posted.

Going back to the HitBTC TX, can you please post the transaction ID here so I can look it up on the explorer or please do so yourself and see if it has been seen on the network.

**Comment by gamesdevhouse** [comment]
i did check on explorer but it doesn’t show there . can you please tell me how to fix balance issue ? Maybe wallet is not sync good thats why balance is incorrect or maybe any command to run to fix this issue . 🙏

**Comment by gamesdevhouse** [comment]
Also I tried using chrome extension wallet . but it doesn’t work also 

You can see there is balance inside wallet but not sending 

https://explorer.htmlcoin.com/address/HikjFnk772wPvH2V8mMyth6g9hVntsjKSA




Sent from Mail for Windows 10

**Comment by Bushstar** [comment]
Sounds like the TX is stuck unconfirmed and the balance is now not present in your wallet. In the transaction list see if you can right client and select "Abandon Transaction", if you can that will return funds. If not then you will need to start the client with the following flag zapwallettxes=1. Add this to your htmlcoin.conf file, this is located in your HTMLCOIN data directory in your roaming profile directory, this is the directory where your wallets folder or wallet.dat is located as well as blockchain data. It is likely that this file does not exist and that you will need to create it, this file is a plaintext file, you can use Notepad to create a plaintext file, when saving please make sure to not save as a .txt file as this will not work. The only line you need in the file is as follows.

`zapwallettxes=1`

After starting the client it should delete all wallet TXs and rescan the entire blockchain for TXs relating to the keys in your wallet restoring your balance, if this process does not appear to happen when the client starts then check the conf file was created properly. After it starts remove the line from the conf file.

**Comment by wpw420** [comment]
I did not send this my shit was hacked by my husband and his friend.
