### ISSUE TITLE
Multiple mentions of QTUM in korean translation file.

### ISSUE THREAD

**Issue by Kraay89** [HTMLCOIN/HTMLCOIN#87]
The korean translation file in ../src/qt/locale/bitcoin_ko.ts contains multiple mentions of [QTUM](https://github.com/HTMLCOIN/HTMLCOIN/blob/master-2.5/src/qt/locale/bitcoin_ko.ts#L151) (click for example). This seems like a relatively easy find/replace fix.

**Comment by denuoweb** [comment]
done, are there any other little issues that you could do but you want someone else to do?

**Comment by denuoweb** [comment]
You can close this issue, it is fixed as of v2.5.2
