### ISSUE TITLE
Please include checksums on site for downloading.

### ISSUE THREAD

**Issue by Datapotomus** [HTMLCOIN/HTMLCOIN#9]
On the website please also add the checksums for the files. This ensures a little more trust in what you are downloading is correct.

**Comment by sunk818** [comment]
What do you use to generate checksums? Is there a standard util that is universal across Windows, Mac, & Linux? Can you recommend something? Maybe you can fork this project, edit the README, and do a pull request?

**Comment by Datapotomus** [comment]
In windows there is Certutil. I can add it to the readme, but you are
really going to want them posted on the site so that way people know they
are genuine.

**Comment by Bushstar** [comment]
I'll pass this on to the website people to add checksums.
